import { boolean, index, int, longtext, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;

export const profiles = mysqlTable("profiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), username: varchar("username", { length: 40 }).notNull(), avatarUrl: varchar("avatarUrl", { length: 500 }), unitSystem: mysqlEnum("unitSystem", ["metric", "imperial"]).default("metric").notNull(), timezone: varchar("timezone", { length: 64 }).default("Australia/Sydney").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ userIdx: uniqueIndex("profiles_user_idx").on(t.userId), usernameIdx: uniqueIndex("profiles_username_idx").on(t.username) }));
export const goals = mysqlTable("goals", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), currentWeight: varchar("currentWeight", { length: 32 }), goalWeight: varchar("goalWeight", { length: 32 }), pace: mysqlEnum("pace", ["cautious", "steady", "slower"]), primaryGoal: varchar("primaryGoal", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ userIdx: index("goals_user_idx").on(t.userId) }));
export const privacySettings = mysqlTable("privacy_settings", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), routeRetention: mysqlEnum("routeRetention", ["one_day", "seven_days", "thirty_days", "manual"]).default("one_day").notNull(), allDayBreadcrumbs: boolean("allDayBreadcrumbs").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ userIdx: uniqueIndex("privacy_user_idx").on(t.userId) }));
export const healthPermissions = mysqlTable("health_permissions", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), provider: varchar("provider", { length: 40 }).notNull(), categories: text("categories").notNull(), grantedAt: timestamp("grantedAt"), revokedAt: timestamp("revokedAt") }, (t) => ({ userIdx: uniqueIndex("health_permissions_user_provider_idx").on(t.userId, t.provider) }));

export const friendships = mysqlTable("friendships", { id: int("id").autoincrement().primaryKey(), requesterId: int("requesterId").notNull(), addresseeId: int("addresseeId").notNull(), status: mysqlEnum("status", ["pending", "accepted", "declined", "blocked", "cancelled"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ pairIdx: uniqueIndex("friendships_pair_idx").on(t.requesterId, t.addresseeId), addresseeIdx: index("friendships_addressee_idx").on(t.addresseeId) }));
export const sharePermissions = mysqlTable("share_permissions", { id: int("id").autoincrement().primaryKey(), ownerId: int("ownerId").notNull(), friendId: int("friendId").notNull(), category: varchar("category", { length: 60 }).notNull(), enabled: boolean("enabled").default(false).notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ pairCategoryIdx: uniqueIndex("share_pair_category_idx").on(t.ownerId, t.friendId, t.category) }));

export const workoutPlans = mysqlTable("workout_plans", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), daysPerWeek: int("daysPerWeek").notNull(), focusJson: text("focusJson").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ userIdx: index("workout_plans_user_idx").on(t.userId) }));
export const workoutSessions = mysqlTable("workout_sessions", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), activityType: varchar("activityType", { length: 40 }), title: varchar("title", { length: 160 }).notNull(), status: mysqlEnum("status", ["planned", "active", "completed", "skipped"]).default("planned").notNull(), startedAt: timestamp("startedAt"), finishedAt: timestamp("finishedAt"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ userIdx: index("workout_sessions_user_idx").on(t.userId), statusIdx: index("workout_sessions_status_idx").on(t.status) }));
export const workoutSets = mysqlTable("workout_sets", { id: int("id").autoincrement().primaryKey(), sessionId: int("sessionId").notNull(), exerciseName: varchar("exerciseName", { length: 160 }).notNull(), weight: varchar("weight", { length: 32 }), reps: int("reps"), rpe: varchar("rpe", { length: 16 }), restSeconds: int("restSeconds"), completedAt: timestamp("completedAt") }, (t) => ({ sessionIdx: index("workout_sets_session_idx").on(t.sessionId) }));
export const activitySummaries = mysqlTable("activity_summaries", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), activityDate: varchar("activityDate", { length: 10 }).notNull(), steps: int("steps").default(0).notNull(), distanceMeters: int("distanceMeters").default(0).notNull(), activeMinutes: int("activeMinutes").default(0).notNull(), activeCalories: int("activeCalories").default(0).notNull(), source: varchar("source", { length: 40 }).notNull(), externalId: varchar("externalId", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ dateIdx: uniqueIndex("activity_user_date_source_idx").on(t.userId, t.activityDate, t.source) }));
export const routes = mysqlTable("routes", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), sessionId: int("sessionId"), routeDate: varchar("routeDate", { length: 10 }).notNull(), isAllDay: boolean("isAllDay").default(false).notNull(), retention: varchar("retention", { length: 20 }).notNull(), deletedAt: timestamp("deletedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ userDateIdx: index("routes_user_date_idx").on(t.userId, t.routeDate) }));
export const routePoints = mysqlTable("route_points", { id: int("id").autoincrement().primaryKey(), routeId: int("routeId").notNull(), latitude: varchar("latitude", { length: 32 }).notNull(), longitude: varchar("longitude", { length: 32 }).notNull(), recordedAt: timestamp("recordedAt").notNull() }, (t) => ({ routeIdx: index("route_points_route_idx").on(t.routeId) }));

export const foods = mysqlTable("foods", { id: int("id").autoincrement().primaryKey(), barcode: varchar("barcode", { length: 64 }), name: varchar("name", { length: 255 }).notNull(), source: varchar("source", { length: 80 }).notNull(), nutritionJson: text("nutritionJson"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ barcodeIdx: index("foods_barcode_idx").on(t.barcode) }));
export const meals = mysqlTable("meals", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), foodId: int("foodId"), name: varchar("name", { length: 160 }).notNull(), portionsJson: text("portionsJson"), loggedAt: timestamp("loggedAt").defaultNow().notNull() }, (t) => ({ userIdx: index("meals_user_idx").on(t.userId) }));
export const supplements = mysqlTable("supplements", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), barcode: varchar("barcode", { length: 64 }), name: varchar("name", { length: 160 }).notNull(), labelJson: text("labelJson"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ userIdx: index("supplements_user_idx").on(t.userId) }));
export const supplementSchedules = mysqlTable("supplement_schedules", { id: int("id").autoincrement().primaryKey(), supplementId: int("supplementId").notNull(), timing: varchar("timing", { length: 40 }).notNull(), reminderEnabled: boolean("reminderEnabled").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ supplementIdx: index("supplement_schedules_supplement_idx").on(t.supplementId) }));

export const challenges = mysqlTable("challenges", { id: int("id").autoincrement().primaryKey(), creatorId: int("creatorId").notNull(), title: varchar("title", { length: 160 }).notNull(), metric: varchar("metric", { length: 50 }).notNull(), duration: mysqlEnum("duration", ["day", "week", "month"]).notNull(), blind: boolean("blind").default(true).notNull(), startsAt: timestamp("startsAt").notNull(), endsAt: timestamp("endsAt").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ creatorIdx: index("challenges_creator_idx").on(t.creatorId), endsIdx: index("challenges_ends_idx").on(t.endsAt) }));
export const challengeParticipants = mysqlTable("challenge_participants", { id: int("id").autoincrement().primaryKey(), challengeId: int("challengeId").notNull(), userId: int("userId").notNull(), status: mysqlEnum("status", ["invited", "accepted", "declined"]).default("invited").notNull(), finalScore: int("finalScore"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ participantIdx: uniqueIndex("challenge_participant_idx").on(t.challengeId, t.userId) }));
export const userData = mysqlTable("user_data", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  namespace: varchar("namespace", { length: 80 }).notNull(),
  payloadJson: longtext("payloadJson").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, (t) => ({
  ownerNamespaceIdx: uniqueIndex("user_data_owner_namespace_idx").on(t.userId, t.namespace),
  ownerIdx: index("user_data_owner_idx").on(t.userId),
}));

export const feedback = mysqlTable("feedback", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), category: mysqlEnum("category", ["feature", "issue", "change"]).notNull(), message: text("message").notNull(), contactAllowed: boolean("contactAllowed").default(false).notNull(), status: mysqlEnum("status", ["new", "reviewing", "planned", "closed"]).default("new").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ userIdx: index("feedback_user_idx").on(t.userId), statusIdx: index("feedback_status_idx").on(t.status) }));

export type UserData = typeof userData.$inferSelect; export type Profile = typeof profiles.$inferSelect; export type Goal = typeof goals.$inferSelect; export type Friendship = typeof friendships.$inferSelect; export type WorkoutSession = typeof workoutSessions.$inferSelect; export type Feedback = typeof feedback.$inferSelect;
