import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { HEALTH_CATEGORIES, loadHealthSnapshot, type HealthCategory, type HealthSyncSnapshot } from "@/lib/healthkit";
const mint = "#B8F36B"; const muted = "#A8B3A6"; const userKey = (user: { openId?: string; id?: number } | null) => user?.openId ?? (user?.id ? String(user.id) : "local-user"); const date = (value?: string) => value ? new Date(value).toLocaleString("en-AU") : "Not available";
export default function HealthDiagnosticsScreen() { const { user } = useAuth({ autoFetch: false }); const [snapshot, setSnapshot] = useState<HealthSyncSnapshot>(); useEffect(() => { void loadHealthSnapshot(userKey(user)).then(setSnapshot); }, [user]); const d = snapshot?.diagnostics; return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>HEALTH DIAGNOSTICS</Text><Text style={styles.title}>Know what synced, and when.</Text><Text style={styles.subtitle}>Diagnostics contain timing, counts, and non-sensitive errors only. Raw HealthKit records and tokens are never logged.</Text><View style={styles.card}><Text style={styles.cardTitle}>Connection</Text><Row label="Status" value={snapshot?.status ?? "Loading"}/><Row label="Last attempted" value={date(d?.lastAttemptedAt)}/><Row label="Last successful" value={date(d?.lastSyncedAt)}/><Row label="Records received" value={String(d?.recordsReceived ?? 0)}/><Row label="Cache written" value={date(d?.cacheWrittenAt)}/><Row label="Latest error" value={d?.lastError ?? "None recorded"}/></View><View style={styles.card}><Text style={styles.cardTitle}>Enabled categories</Text>{(d?.enabledCategories ?? []).map((key: HealthCategory) => <View key={key} style={styles.row}><Text style={styles.label}>{HEALTH_CATEGORIES[key].label}</Text><Text style={styles.enabled}>Enabled</Text></View>)}</View><View style={styles.notice}><Text style={styles.noticeTitle}>Apple controls permissions</Text><Text style={styles.noticeText}>A category can be requested while iOS still limits what HealthKit discloses. Revoke access in iPhone Settings › Health › Data Access & Devices › VELTURA.</Text></View></ScrollView></ScreenContainer>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 32, gap: 16 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "#F4F7F0", fontSize: 29, lineHeight: 35, fontWeight: "900" }, subtitle: { color: muted, fontSize: 13, lineHeight: 19 }, card: { backgroundColor: "rgba(66, 132, 174, 0.38)", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.46)", gap: 9 }, cardTitle: { color: "#F4F7F0", fontSize: 17, fontWeight: "900" }, row: { flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: "#263128" }, label: { color: muted, flex: 1, fontSize: 12 }, value: { color: "#F4F7F0", flex: 1, textAlign: "right", fontSize: 12, fontWeight: "700" }, enabled: { color: mint, fontSize: 11, fontWeight: "800" }, notice: { backgroundColor: "rgba(76, 143, 184, 0.40)", borderRadius: 17, padding: 15, borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.54)" }, noticeTitle: { color: "#F7CF77", fontWeight: "900" }, noticeText: { color: muted, fontSize: 11, lineHeight: 17, marginTop: 6 } });
