import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { KINGS_GYM_EQUIPMENT, LocalGymRepository, GENERIC_EQUIPMENT_CATALOGUE, recommendMachineProgression, type GymEquipmentInstance } from "@/lib/gym-directory";
const mint = "#B8F36B"; const muted = "#A8B3A6"; const repository = new LocalGymRepository();
export default function EquipmentProfileScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { user } = useAuth({ autoFetch: false }); const userId = user?.openId ?? (user?.id ? String(user.id) : "local-user"); const [equipment, setEquipment] = useState<GymEquipmentInstance>(); const [message, setMessage] = useState(""); const [history, setHistory] = useState<Awaited<ReturnType<LocalGymRepository["listHistory"]>>>([]);
  useEffect(() => { void (async () => { const inventory = await repository.listEquipment("fixture-kings-gym-glen-innes"); setEquipment(inventory.find((item) => item.id === id) ?? KINGS_GYM_EQUIPMENT.find((item) => item.id === id)); setHistory(await repository.listHistory(userId, id)); })(); }, [id, userId]);
  if (!equipment) return <ScreenContainer className="px-5 pt-4"><Text style={styles.title}>Machine not found</Text><Text style={styles.copy}>This listing may be unavailable offline or may have been removed.</Text></ScreenContainer>;
  const generic = GENERIC_EQUIPMENT_CATALOGUE.find((item) => item.id === equipment.genericEquipmentTypeId); const recommendation = recommendMachineProgression(history, equipment.availableWeightIncrements);
  const confirm = async () => { await repository.confirmEquipment({ id: `confirmation-${Date.now()}`, gymId: equipment.gymId, equipmentInstanceId: equipment.id, confirmedAt: new Date().toISOString(), userId }); setEquipment({ ...equipment, availability: "Available", verificationStatus: equipment.verificationStatus === "Unverified" ? "Community confirmed" : equipment.verificationStatus, confirmationCount: equipment.confirmationCount + 1, lastConfirmedAt: new Date().toISOString() }); setMessage("Confirmation saved privately to your account and reflected in the community count."); };
  const report = async (status: "Temporarily broken" | "Removed" | "Replaced" | "Disputed") => { await repository.reportEquipment({ id: `report-${Date.now()}`, gymId: equipment.gymId, equipmentInstanceId: equipment.id, status, createdAt: new Date().toISOString(), photoIds: [], userId }); setEquipment({ ...equipment, availability: status, verificationStatus: "Disputed" }); setMessage(`Report saved as ${status}. Existing listing was not silently overwritten.`); };
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Equipment inventory</Text></Pressable><Text style={styles.eyebrow}>MACHINE PROFILE</Text><Text style={styles.title}>{equipment.nickname ?? generic?.name ?? "Equipment"}</Text><Text style={styles.copy}>{generic?.category} · {equipment.verificationStatus} · {equipment.availability}</Text><View style={styles.card}><Text style={styles.label}>SETUP</Text><Text style={styles.copy}>{equipment.setupInstructions}</Text><Text style={styles.label}>MOVEMENT</Text><Text style={styles.copy}>{equipment.movementInstructions}</Text><Text style={styles.label}>SAFETY</Text><Text style={styles.copy}>{equipment.safetyGuidance}</Text></View><View style={styles.card}><Text style={styles.label}>COMPATIBLE EXERCISES</Text>{equipment.compatibleExerciseIds.slice(0, 8).map((exerciseId) => <Pressable key={exerciseId} onPress={() => router.push({ pathname: "/exercise/[id]", params: { id: exerciseId } } as any)}><Text style={styles.exercise}>View exercise demonstration · {exerciseId}</Text></Pressable>)}</View><View style={styles.card}><Text style={styles.label}>YOUR MACHINE HISTORY</Text>{history.length ? <><Text style={styles.copy}>Last used {new Date(history[history.length - 1].performedAt).toLocaleDateString()} · {history[history.length - 1].resistance ?? "—"} {history[history.length - 1].unit}</Text><Text style={styles.copy}>{history[history.length - 1].sets.length} sets · private to your account</Text></> : <Text style={styles.copy}>No private performance history yet.</Text>}<Text style={styles.recommendation}>{recommendation.action === "increase" ? `Suggested today: ${recommendation.resistance} ${recommendation.unit}` : "Suggested today: repeat a controlled resistance"}</Text><Text style={styles.copy}>{recommendation.explanation}</Text></View><View style={styles.row}><Pressable style={styles.button} onPress={() => void confirm()}><Text style={styles.buttonText}>Confirm present</Text></Pressable><Pressable style={styles.secondary} onPress={() => void report("Temporarily broken")}><Text style={styles.secondaryText}>Report broken</Text></Pressable></View><View style={styles.row}><Pressable style={styles.secondary} onPress={() => void report("Removed")}><Text style={styles.secondaryText}>Report removed</Text></Pressable><Pressable style={styles.secondary} onPress={() => void report("Replaced")}><Text style={styles.secondaryText}>Report replaced</Text></Pressable></View>{message ? <Text style={styles.message}>{message}</Text> : null}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 13, paddingBottom: 35 }, back: { color: mint, fontWeight: "800" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { color: "#F4F7F0", fontSize: 28, fontWeight: "900" }, copy: { color: muted, lineHeight: 18, fontSize: 12 }, card: { gap: 8, padding: 15, borderRadius: 17, backgroundColor: "rgba(66,132,174,.38)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)" }, label: { color: mint, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, exercise: { color: "#DDF3FF", fontSize: 12, paddingVertical: 4 }, recommendation: { color: "#F4F7F0", fontWeight: "900", marginTop: 4 }, row: { flexDirection: "row", gap: 8 }, button: { flex: 1, padding: 13, borderRadius: 13, backgroundColor: mint, alignItems: "center" }, buttonText: { color: "#10202A", fontWeight: "900", fontSize: 11 }, secondary: { flex: 1, padding: 13, borderRadius: 13, backgroundColor: "rgba(10,43,67,.6)", borderWidth: 1, borderColor: mint, alignItems: "center" }, secondaryText: { color: mint, fontWeight: "900", fontSize: 11 }, message: { color: mint, fontSize: 12, lineHeight: 17 } });
