import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { LocalGymRepository, type UserMachineHistory } from "@/lib/gym-directory";
import { useAuth } from "@/hooks/use-auth";
const mint = "#B8F36B"; const muted = "#A8B3A6"; const repository = new LocalGymRepository();
export default function LogMachineScreen() {
  const { id, exerciseId } = useLocalSearchParams<{ id: string; exerciseId?: string }>(); const { user } = useAuth({ autoFetch: false }); const [resistance, setResistance] = useState(""); const [reps, setReps] = useState("10"); const [sets, setSets] = useState("3"); const [rpe, setRpe] = useState(""); const [pain, setPain] = useState(""); const [message, setMessage] = useState("");
  const save = async () => { const record: UserMachineHistory = { id: `history-${Date.now()}`, userId: user?.openId ?? (user?.id ? String(user.id) : "local-user"), gymId: "fixture-kings-gym-glen-innes", equipmentInstanceId: id, exerciseId: exerciseId ?? "unknown-exercise", performedAt: new Date().toISOString(), resistance: Number(resistance) || undefined, unit: "kilograms", sets: Array.from({ length: Math.max(1, Number(sets) || 1) }, () => ({ reps: Math.max(0, Number(reps) || 0), rpe: Number(rpe) || undefined })), completed: true, painOrLimitation: pain.trim() || undefined }; await repository.saveHistory(record); setMessage("Saved privately to your machine history."); };
  return <ScreenContainer className="px-5 pt-4"><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Machine profile</Text></Pressable><Text style={styles.eyebrow}>PRIVATE MACHINE LOG</Text><Text style={styles.title}>Log performance</Text><Text style={styles.copy}>This history is scoped to your account, gym and exact equipment instance.</Text><TextInput style={styles.input} value={resistance} onChangeText={setResistance} placeholder="Resistance / weight" placeholderTextColor="#718071" keyboardType="decimal-pad" /><TextInput style={styles.input} value={sets} onChangeText={setSets} placeholder="Sets" placeholderTextColor="#718071" keyboardType="number-pad" /><TextInput style={styles.input} value={reps} onChangeText={setReps} placeholder="Reps per set" placeholderTextColor="#718071" keyboardType="number-pad" /><TextInput style={styles.input} value={rpe} onChangeText={setRpe} placeholder="RPE (optional)" placeholderTextColor="#718071" keyboardType="decimal-pad" /><TextInput style={styles.input} value={pain} onChangeText={setPain} placeholder="Pain or limitation (optional)" placeholderTextColor="#718071" /><Pressable style={styles.button} onPress={() => void save()}><Text style={styles.buttonText}>Save private performance</Text></Pressable>{message ? <Text style={styles.message}>{message}</Text> : null}</View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 12 }, back: { color: mint, fontWeight: "800" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "900" }, copy: { color: muted, lineHeight: 18 }, input: { backgroundColor: "rgba(10,43,67,.5)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)", borderRadius: 13, padding: 13, color: "#F4F7F0" }, button: { backgroundColor: mint, borderRadius: 14, padding: 15, alignItems: "center" }, buttonText: { color: "#10202A", fontWeight: "900" }, message: { color: mint, lineHeight: 18 } });
