import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
const mint = "#B8F36B"; const muted = "#A8B3A6";
export default function AccountScreen() { const [mode, setMode] = useState<"create" | "signIn">("create"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [submitted, setSubmitted] = useState(false); const valid = email.includes("@") && password.length >= 8; return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.eyebrow}>YOUR ACCOUNT</Text><Text style={styles.title}>{mode === "create" ? "Start your PulseCoach account." : "Welcome back."}</Text><Text style={styles.subtitle}>{mode === "create" ? "Keep your plans, progress, and sharing settings connected." : "Sign in to pick up where you left off."}</Text><View style={styles.switcher}><Pressable onPress={() => { setMode("create"); setSubmitted(false); }} style={[styles.switch, mode === "create" && styles.switchActive]}><Text style={[styles.switchText, mode === "create" && styles.switchTextActive]}>Create account</Text></Pressable><Pressable onPress={() => { setMode("signIn"); setSubmitted(false); }} style={[styles.switch, mode === "signIn" && styles.switchActive]}><Text style={[styles.switchText, mode === "signIn" && styles.switchTextActive]}>Sign in</Text></Pressable></View><Field label="Email address" value={email} onChange={setEmail} keyboard="email-address" /><Field label="Password" value={password} onChange={setPassword} keyboard="default" secure /><Text style={styles.passwordHint}>Use at least 8 characters. Password reset and email verification will be enabled for production account storage.</Text>{submitted ? <View style={styles.success}><Text style={styles.successTitle}>{mode === "create" ? "Account request ready" : "Sign-in request ready"}</Text><Text style={styles.successCopy}>The production provider will verify this account and link any matching Apple, Google, or Facebook identity instead of creating a duplicate.</Text></View> : <Pressable style={[styles.primary, !valid && styles.disabled]} disabled={!valid} onPress={() => setSubmitted(true)}><Text style={styles.primaryText}>{mode === "create" ? "Create account" : "Sign in"}</Text></Pressable>}<Text style={styles.privacy}>By continuing, you agree to review PulseCoach’s privacy, health-data, and account-deletion information before using connected features.</Text></ScrollView></ScreenContainer>; }
function Field({ label, value, onChange, keyboard, secure }: { label: string; value: string; onChange: (v: string) => void; keyboard: "email-address" | "default"; secure?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard} autoCapitalize="none" secureTextEntry={secure} placeholder={label} placeholderTextColor="#718071" style={styles.input} /></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "#F4F7F0", fontSize: 31, lineHeight: 37, fontWeight: "900" }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, switcher: { flexDirection: "row", backgroundColor: "#1B231D", borderRadius: 13, padding: 4, gap: 4 }, switch: { flex: 1, padding: 11, alignItems: "center", borderRadius: 10 }, switchActive: { backgroundColor: "#2B3B27" }, switchText: { color: muted, fontWeight: "800", fontSize: 12 }, switchTextActive: { color: mint }, field: { gap: 6 }, label: { color: muted, fontSize: 11, fontWeight: "700" }, input: { color: "#F4F7F0", backgroundColor: "#1B231D", borderRadius: 13, padding: 14, borderWidth: 1, borderColor: "#2D392E" }, passwordHint: { color: "#718071", fontSize: 10, lineHeight: 15 }, primary: { backgroundColor: mint, borderRadius: 15, padding: 16, alignItems: "center" }, disabled: { opacity: 0.35 }, primaryText: { color: "#111513", fontWeight: "900" }, success: { backgroundColor: "#2B3B27", borderRadius: 16, padding: 15, borderWidth: 1, borderColor: mint }, successTitle: { color: mint, fontWeight: "900" }, successCopy: { color: "#DCE5D8", fontSize: 11, lineHeight: 16, marginTop: 5 }, privacy: { color: "#718071", fontSize: 10, lineHeight: 15, marginTop: 4 }
});
