import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { buildFocusPlan, type WorkoutFocus } from "@/lib/workout-selection";

const mint = "#B8F36B";
const muted = "#A8B3A6";
const focuses: WorkoutFocus[] = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Arms", "Legs", "Glutes", "Core", "Full body", "Cardio", "Run", "Walk", "Cycle", "Mobility/recovery", "Custom workout"];
const stylesList = ["Strength", "Muscle growth", "Endurance", "General fitness", "Recovery"];

export default function ChooseWorkoutScreen() {
  const [focus, setFocus] = useState<WorkoutFocus>("Full body");
  const [minutes, setMinutes] = useState("35");
  const [equipment, setEquipment] = useState("Dumbbells");
  const [style, setStyle] = useState("General fitness");
  const [readiness, setReadiness] = useState("Ready");
  const [limitation, setLimitation] = useState("");
  const plan = useMemo(() => buildFocusPlan(focus, Number(minutes), limitation), [focus, minutes, limitation]);

  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Workout</Text></Pressable><Text style={styles.eyebrow}>SESSION BUILDER</Text><Text style={styles.title}>Choose today’s workout</Text><Text style={styles.subtitle}>Tell PulseCoach what you want from today. Suggestions regenerate when your focus changes.</Text><Text style={styles.label}>Primary focus</Text><View style={styles.chips}>{focuses.map((item) => <Pressable key={item} onPress={() => setFocus(item)} style={[styles.chip, item === focus && styles.chipActive]}><Text style={[styles.chipText, item === focus && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><Text style={styles.label}>Available time</Text><TextInput value={minutes} onChangeText={setMinutes} keyboardType="number-pad" style={styles.input} placeholder="Minutes" placeholderTextColor="#718071" /><Text style={styles.label}>Equipment or gym</Text><TextInput value={equipment} onChangeText={setEquipment} style={styles.input} placeholder="e.g. Full gym" placeholderTextColor="#718071" /><Text style={styles.label}>Workout style</Text><View style={styles.row}>{stylesList.map((item) => <Pressable key={item} onPress={() => setStyle(item)} style={[styles.smallChip, item === style && styles.chipActive]}><Text style={[styles.chipText, item === style && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><Text style={styles.label}>Current energy</Text><View style={styles.row}>{["Low", "Okay", "Ready"].map((item) => <Pressable key={item} onPress={() => setReadiness(item)} style={[styles.smallChip, item === readiness && styles.chipActive]}><Text style={[styles.chipText, item === readiness && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><Text style={styles.label}>Pain or limitation today</Text><TextInput value={limitation} onChangeText={setLimitation} style={[styles.input, styles.multiline]} multiline placeholder="Optional — describe what to protect" placeholderTextColor="#718071" /><View style={styles.preview}><Text style={styles.previewEyebrow}>PREVIEW · {style.toUpperCase()} · {equipment}</Text><Text style={styles.previewTitle}>{plan.focus} session · {plan.minutes} min</Text><Text style={styles.previewCopy}>{plan.exercises.join("  ·  ")}</Text>{plan.changedForLimitation && <Text style={styles.safety}>Adjusted around the limitation you entered. Stop for sharp pain or unusual symptoms.</Text>}</View><Pressable style={styles.confirm} onPress={() => router.replace("/workout" as any)}><Text style={styles.confirmText}>Use this workout</Text></Pressable><Text style={styles.note}>Changing focus replaces the suggestions only. If you have completed sets, PulseCoach will ask whether to continue, save the partial workout, or discard the uncompleted plan.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 36, gap: 12 }, back: { color: mint, fontSize: 15, fontWeight: "800", marginBottom: 8 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: muted, fontSize: 14, lineHeight: 20, marginBottom: 6 }, label: { color: "#F4F7F0", fontSize: 14, fontWeight: "800", marginTop: 8 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 13, backgroundColor: "#1B231D", borderWidth: 1, borderColor: "#2D392E" }, chipActive: { backgroundColor: "#2C3B25", borderColor: mint }, chipText: { color: muted, fontSize: 12, fontWeight: "700" }, chipTextActive: { color: mint }, input: { backgroundColor: "#111513", borderWidth: 1, borderColor: "#2D392E", borderRadius: 13, padding: 13, color: "#F4F7F0", fontSize: 14 }, multiline: { minHeight: 72, textAlignVertical: "top" }, row: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, smallChip: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, backgroundColor: "#1B231D", borderWidth: 1, borderColor: "#2D392E" }, preview: { backgroundColor: "#202A21", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#354536", gap: 8, marginTop: 6 }, previewEyebrow: { color: mint, fontSize: 10, fontWeight: "800", letterSpacing: 1 }, previewTitle: { color: "#F4F7F0", fontSize: 18, fontWeight: "800" }, previewCopy: { color: muted, fontSize: 12, lineHeight: 18 }, safety: { color: "#F7CF77", fontSize: 11, lineHeight: 16 }, confirm: { backgroundColor: mint, borderRadius: 15, alignItems: "center", padding: 15, marginTop: 4 }, confirmText: { color: "#111513", fontWeight: "900", fontSize: 15 }, note: { color: "#718071", fontSize: 11, lineHeight: 16 }
});
