import { useCallback, useEffect, useRef, useState } from "react";
import * as Location from "expo-location";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { loadProfilePreferences, saveProfilePreferences } from "@/lib/profile-preferences";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAuth } from "@/hooks/use-auth";
import { KINGS_GYM_GLEN_INNES, LocalGymRepository, mergeGymSearchResults, type ExternalGymSearchResult, type Gym, type GymEquipmentInstance } from "@/lib/gym-directory";
import { trpc } from "@/lib/trpc";

const mint = "#B8F36B"; const muted = "#A8B3A6"; const repository = new LocalGymRepository();
const userKey = (user: { openId?: string; id?: number } | null) => user?.openId ?? (user?.id ? String(user.id) : "local-user");

export default function GymDirectoryScreen() {
  const { user } = useAuth();
  const trpcUtils = trpc.useUtils();
  const [query, setQuery] = useState(""); const [gyms, setGyms] = useState<Gym[]>([]); const [selected, setSelected] = useState<Gym>(); const [inventory, setInventory] = useState<GymEquipmentInstance[]>([]);
  const [message, setMessage] = useState(""); const [locationDenied, setLocationDenied] = useState(false); const [locationBias, setLocationBias] = useState<{ latitude: number; longitude: number }>(); const [searching, setSearching] = useState(false); const [searchFailed, setSearchFailed] = useState(false); const [liveStatus, setLiveStatus] = useState<"configured" | "unconfigured" | "offline" | "error">("configured"); const [externalResults, setExternalResults] = useState<ExternalGymSearchResult[]>([]); const [selectedExternal, setSelectedExternal] = useState<ExternalGymSearchResult>(); const [nextPageToken, setNextPageToken] = useState<string>();
  const [showCreate, setShowCreate] = useState(false); const [duplicateCandidates, setDuplicateCandidates] = useState<Gym[]>([]);
  const searchSequence = useRef(0);
  const [newName, setNewName] = useState(""); const [newAddress, setNewAddress] = useState(""); const [newSuburb, setNewSuburb] = useState(""); const [newState, setNewState] = useState("NSW"); const [newPostcode, setNewPostcode] = useState(""); const [newLatitude, setNewLatitude] = useState(""); const [newLongitude, setNewLongitude] = useState(""); const [newWebsite, setNewWebsite] = useState(""); const [newPhone, setNewPhone] = useState("");
  const search = useCallback(async (value = query, pageToken?: string) => { const sequence = ++searchSequence.current; setQuery(value); if (value.trim().length < 2) { setGyms([]); setExternalResults([]); return; } setSearching(true); setSearchFailed(false); try { const saved = await repository.searchGyms(value); const live = await trpcUtils.gym.search.fetch({ query: value, pageToken, ...locationBias }); if (sequence !== searchSequence.current) return; setGyms(saved); setLiveStatus(live.status); const combined = mergeGymSearchResults(saved, live.results as ExternalGymSearchResult[]); setExternalResults(combined.flatMap((entry) => entry.source === "external" && entry.external ? [entry.external] : [])); setNextPageToken(live.nextPageToken); } catch { if (sequence === searchSequence.current) { setLiveStatus("offline"); setExternalResults([]); setSearchFailed(false); } } finally { if (sequence === searchSequence.current) setSearching(false); } }, [query, trpcUtils, locationBias]);
  useEffect(() => { if (query.trim().length < 2) return; const timer = setTimeout(() => void search(query), 350); return () => clearTimeout(timer); }, [query, search]);
  const selectGym = useCallback(async (gym: Gym) => { setSelected(gym); setInventory(await repository.listEquipment(gym.id)); setMessage(""); }, []);
  useEffect(() => { void (async () => { const saved = user ? (await loadProfilePreferences(userKey(user))).currentGymId : undefined; const gym = saved ? await repository.getGym(saved) : undefined; if (gym) await selectGym(gym); })().catch(() => setMessage("Could not load your saved gym.")); }, [selectGym, user]);
  const saveSelection = async (kind: "home" | "current") => { if (!selected) return; if (!user) { setMessage("Sign in to save gym preferences."); return; } try { const profile = await loadProfilePreferences(userKey(user)); await saveProfilePreferences(userKey(user), { ...profile, [kind === "home" ? "homeGym" : "currentGym"]: selected.name, [kind === "home" ? "homeGymId" : "currentGymId"]: selected.id }); } catch { setMessage("Could not save your gym. Check your connection and Personal Details."); return; } setMessage(`${kind === "home" ? "Home" : "Current training"} gym saved.`); };
  const findNearby = async () => { setMessage("Requesting foreground location only…"); try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") { setLocationDenied(true); setMessage("Location is unavailable. Search manually by gym, suburb or postcode."); return; } const location = await Location.getCurrentPositionAsync({}); setLocationBias({ latitude: location.coords.latitude, longitude: location.coords.longitude }); const nearby = await repository.nearbyGyms(location.coords.latitude, location.coords.longitude); setGyms(nearby.map((gym) => ({ ...gym, distanceKm: gym.latitude !== undefined && gym.longitude !== undefined ? Math.hypot((gym.latitude - location.coords.latitude) * 111, (gym.longitude - location.coords.longitude) * 90) : undefined }))); setLocationDenied(false); setMessage("Nearby gyms loaded."); } catch { setMessage("Nearby search failed. Manual search remains available."); } };
  const createGym = async (confirmDifferent = false) => { if (!newName.trim() || !newAddress.trim() || !newSuburb.trim() || !newPostcode.trim()) { setMessage("Gym name, street address, suburb and postcode are required."); return; } const latitude = Number(newLatitude); const longitude = Number(newLongitude); const input = { name: newName.trim(), streetAddress: newAddress.trim(), suburb: newSuburb.trim(), state: newState.trim() || "NSW", postcode: newPostcode.trim(), country: "Australia", createdBy: "community" as const, ...(Number.isFinite(latitude) ? { latitude } : {}), ...(Number.isFinite(longitude) ? { longitude } : {}), ...(newWebsite.trim() ? { website: newWebsite.trim() } : {}), ...(newPhone.trim() ? { phone: newPhone.trim() } : {}) }; const result = await repository.createGym(input, { confirmDifferent }); if (result.possibleDuplicates.length && !confirmDifferent) { setDuplicateCandidates(result.possibleDuplicates); setGyms(result.possibleDuplicates); setMessage("Possible duplicate gyms found. Select one, or confirm the new gym is different."); return; } if (result.gym) { await selectGym(result.gym); setShowCreate(false); setDuplicateCandidates([]); setNewName(""); setNewAddress(""); setNewSuburb(""); setNewPostcode(""); setMessage("Community gym created as unverified."); } };
  const saveExternal = async () => { if (!selectedExternal) return; const existing = (await repository.searchGyms(selectedExternal.name)).find((gym) => gym.externalProvider === selectedExternal.provider && gym.externalPlaceId === selectedExternal.placeId); if (existing) { await selectGym(existing); setSelectedExternal(undefined); setMessage("This gym is already saved in PulseCoach."); return; } const result = await repository.createGym({ name: selectedExternal.name, streetAddress: selectedExternal.formattedAddress, suburb: selectedExternal.suburb ?? "", state: selectedExternal.state ?? "", postcode: selectedExternal.postcode ?? "", country: selectedExternal.country ?? "Australia", latitude: selectedExternal.latitude, longitude: selectedExternal.longitude, createdBy: "community", externalProvider: selectedExternal.provider, externalPlaceId: selectedExternal.placeId }); if (result.gym) { await selectGym(result.gym); setSelectedExternal(undefined); setMessage("Gym saved to PulseCoach. No equipment registered yet."); } else if (result.possibleDuplicates.length) { await selectGym(result.possibleDuplicates[0]); setSelectedExternal(undefined); setMessage("This gym is already represented in PulseCoach."); } };
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>COMMUNITY GYM DIRECTORY</Text><Text style={styles.title}>Choose where you train.</Text><Text style={styles.subtitle}>Search the community directory, or opt in to a one-time foreground nearby search.</Text>
    <View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} placeholder="Search gym, town or postcode" placeholderTextColor="#718071" style={styles.input} /><Pressable style={styles.nearby} onPress={() => void findNearby()}><IconSymbol name="location.fill" size={18} color="#10202A" /></Pressable></View>
    {locationDenied ? <Text style={styles.warning}>Location permission was denied. Manual search remains available.</Text> : null}{searching ? <Text style={styles.empty}>Searching the community directory…</Text> : null}{searchFailed ? <Text style={styles.warning}>The directory is unavailable offline. Try again or add this gym manually.</Text> : null}{query.trim() && !searching && !searchFailed && gyms.length === 0 ? <Text style={styles.empty}>No matching community gyms. You can add this gym below.</Text> : null}{message ? <Text style={styles.message}>{message}</Text> : null}
    <Pressable style={styles.fixture} onPress={() => void selectGym(KINGS_GYM_GLEN_INNES)}><Text style={styles.fixtureTitle}>Development fixture: Kings Gym Glen Innes</Text><Text style={styles.fixtureCopy}>Clearly labelled test data; not verified real-world information.</Text></Pressable>
    {gyms.map((gym) => <Pressable key={gym.id} style={[styles.gymCard, selected?.id === gym.id && styles.active]} onPress={() => void selectGym(gym)}><Text style={styles.cardTitle}>{gym.name}</Text><Text style={styles.cardCopy}>{gym.streetAddress}, {gym.suburb}, {gym.state} {gym.postcode} · Saved in PulseCoach · {gym.verificationStatus}{gym.distanceKm !== undefined ? ` · ${gym.distanceKm.toFixed(1)} km` : ""}</Text></Pressable>)}
    {liveStatus === "unconfigured" ? <Text style={styles.warning}>Live gym search is not configured.</Text> : null}{liveStatus === "offline" ? <Text style={styles.warning}>Live search is unavailable offline. Saved community gyms are still searchable.</Text> : null}{liveStatus === "error" ? <Text style={styles.warning}>Live provider search failed. Try again or add this gym manually.</Text> : null}
    {externalResults.map((gym) => <Pressable key={`${gym.provider}-${gym.placeId}`} style={styles.gymCard} onPress={() => setSelectedExternal(gym)}><Text style={styles.cardTitle}>{gym.name}</Text><Text style={styles.cardCopy}>{gym.formattedAddress} · External result{gym.businessStatus && gym.businessStatus !== "OPERATIONAL" ? ` · ${gym.businessStatus.toLowerCase()}` : ""}{gym.distanceKm !== undefined ? ` · ${gym.distanceKm.toFixed(1)} km` : ""}</Text></Pressable>)}
    {nextPageToken ? <Pressable style={styles.secondaryButton} onPress={() => void search(query, nextPageToken)}><Text style={styles.secondaryText}>Load more live gyms</Text></Pressable> : null}
    {selectedExternal ? <View style={styles.selected}><Text style={styles.section}>EXTERNAL GYM DETAILS</Text><Text style={styles.cardTitle}>{selectedExternal.name}</Text><Text style={styles.cardCopy}>{selectedExternal.formattedAddress}</Text><Text style={styles.cardCopy}>Not saved in PulseCoach yet. No equipment registered yet.</Text><Pressable style={styles.button} onPress={() => void saveExternal()}><Text style={styles.buttonText}>Confirm and save gym</Text></Pressable></View> : null}
    <Pressable style={styles.secondaryButton} onPress={() => setShowCreate((value) => !value)}><Text style={styles.secondaryText}>{showCreate ? "Hide create gym" : "Can’t find your gym? Create it"}</Text></Pressable>
    {showCreate ? <View style={styles.form}><TextInput value={newName} onChangeText={setNewName} placeholder="Gym name" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newAddress} onChangeText={setNewAddress} placeholder="Street address" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newSuburb} onChangeText={setNewSuburb} placeholder="Town or suburb" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newState} onChangeText={setNewState} placeholder="State" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newPostcode} onChangeText={setNewPostcode} placeholder="Australian postcode" keyboardType="number-pad" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newLatitude} onChangeText={setNewLatitude} placeholder="Latitude (optional)" keyboardType="numbers-and-punctuation" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newLongitude} onChangeText={setNewLongitude} placeholder="Longitude (optional)" keyboardType="numbers-and-punctuation" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newWebsite} onChangeText={setNewWebsite} placeholder="Website (optional)" placeholderTextColor="#718071" style={styles.input} /><TextInput value={newPhone} onChangeText={setNewPhone} placeholder="Phone (optional)" keyboardType="phone-pad" placeholderTextColor="#718071" style={styles.input} /><Pressable style={styles.button} onPress={() => void createGym()}><Text style={styles.buttonText}>Check duplicates and create</Text></Pressable>{duplicateCandidates.length ? <Pressable style={styles.secondaryButton} onPress={() => void createGym(true)}><Text style={styles.secondaryText}>Create anyway — this is different</Text></Pressable> : null}</View> : null}
    {selected ? <><Text style={styles.section}>SELECTED GYM</Text><View style={styles.selected}><Text style={styles.cardTitle}>{selected.name}</Text><Text style={styles.cardCopy}>{selected.streetAddress}, {selected.suburb}, {selected.state} {selected.postcode} · {selected.verificationStatus}</Text><View style={styles.row}><Pressable style={styles.smallButton} onPress={() => void saveSelection("home")}><Text style={styles.smallText}>Set home gym</Text></Pressable><Pressable style={styles.smallButton} onPress={() => void saveSelection("current")}><Text style={styles.smallText}>Training here</Text></Pressable></View></View><Text style={styles.section}>EQUIPMENT INVENTORY ({inventory.length})</Text>{inventory.length ? inventory.map((item) => <Pressable key={item.id} style={styles.equipment} onPress={() => router.push({ pathname: "/equipment/[id]", params: { id: item.id } } as any)}><View style={styles.flex}><Text style={styles.cardTitle}>{item.nickname ?? item.genericEquipmentTypeId}</Text><Text style={styles.cardCopy}>{item.availability} · {item.verificationStatus} · {item.confirmationCount} confirmations</Text></View><IconSymbol name="chevron.right" size={18} color={mint} /></Pressable>) : <Text style={styles.empty}>No equipment is listed yet. Add the first machine by photographing it.</Text>}<Pressable style={styles.scan} onPress={() => router.push({ pathname: "/machine", params: { gymId: selected.id } } as any)}><IconSymbol name="camera.fill" size={20} color="#10202A" /><Text style={styles.buttonText}>Scan or add equipment</Text></Pressable></> : null}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 40, gap: 12 }, back: { color: mint, fontWeight: "800" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "900" }, subtitle: { color: muted, lineHeight: 19 }, searchRow: { flexDirection: "row", gap: 8 }, input: { flex: 1, backgroundColor: "rgba(10,43,67,.5)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)", borderRadius: 13, padding: 13, color: "#F4F7F0" }, nearby: { width: 50, borderRadius: 13, backgroundColor: mint, alignItems: "center", justifyContent: "center" }, warning: { color: "#F7CF77", fontSize: 12 }, message: { color: mint, fontSize: 12 }, fixture: { padding: 14, borderRadius: 15, backgroundColor: "rgba(39,78,108,.72)", borderWidth: 1, borderColor: "#87C7E8" }, fixtureTitle: { color: "#F4F7F0", fontWeight: "900" }, fixtureCopy: { color: muted, fontSize: 11, marginTop: 4 }, gymCard: { padding: 14, borderRadius: 15, backgroundColor: "rgba(66,132,174,.38)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)" }, active: { borderColor: mint, backgroundColor: "#2C3B25" }, cardTitle: { color: "#F4F7F0", fontWeight: "900" }, cardCopy: { color: muted, fontSize: 11, marginTop: 4, lineHeight: 16 }, secondaryButton: { alignItems: "center", padding: 10 }, secondaryText: { color: mint, fontWeight: "800" }, form: { gap: 8 }, button: { backgroundColor: mint, borderRadius: 14, padding: 14, alignItems: "center" }, buttonText: { color: "#10202A", fontWeight: "900" }, section: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.1, marginTop: 10 }, selected: { gap: 9, padding: 14, borderRadius: 16, backgroundColor: "#2C3B25", borderWidth: 1, borderColor: mint }, row: { flexDirection: "row", gap: 8 }, smallButton: { flex: 1, padding: 10, borderRadius: 11, backgroundColor: "rgba(10,43,67,.55)", alignItems: "center" }, smallText: { color: mint, fontSize: 11, fontWeight: "800" }, equipment: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14, borderRadius: 15, backgroundColor: "rgba(66,132,174,.38)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)" }, flex: { flex: 1 }, empty: { color: muted, lineHeight: 18 }, scan: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, padding: 15, borderRadius: 15, backgroundColor: mint, marginTop: 4 } });
