import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, AppState, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAuth } from "@/hooks/use-auth";
import { DEFAULT_HEALTH_PREFERENCES, HEALTH_CATEGORIES, deleteImportedHealthData, disconnectHealth, loadHealthSnapshot, requestHealthAuthorization, saveHealthPreferences, startHealthObservers, syncHealthData, type HealthCategory, type HealthSyncSnapshot } from "@/lib/healthkit";

const mint = "#B8F36B"; const muted = "#A8B3A6";
const blank = (): HealthSyncSnapshot => ({ status: "not_setup", preferences: DEFAULT_HEALTH_PREFERENCES, diagnostics: { enabledCategories: [], recordsReceived: 0 } });
const storageKey = (user: { openId?: string; id?: number } | null) => user?.openId ?? (user?.id ? String(user.id) : "local-user");

export default function HealthScreen() {
  const { user } = useAuth({ autoFetch: false }); const userKey = storageKey(user);
  const [snapshot, setSnapshot] = useState<HealthSyncSnapshot>(blank()); const [preferences, setPreferences] = useState(DEFAULT_HEALTH_PREFERENCES); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState(false);
  const sync = useCallback(async (selected = preferences) => { setRefreshing(true); setSnapshot(await syncHealthData(userKey, new Date(), selected)); setRefreshing(false); }, [preferences, userKey]);

  useEffect(() => { let cancelled = false; void loadHealthSnapshot(userKey).then(async (loaded) => { if (cancelled) return; setSnapshot(loaded); setPreferences(loaded.preferences); if (loaded.status === "connected" || loaded.lastSyncedAt) { const refreshed = await syncHealthData(userKey, new Date(), loaded.preferences); if (!cancelled) setSnapshot(refreshed); } }).catch(() => { if (!cancelled) setSnapshot(blank()); }); return () => { cancelled = true; }; }, [userKey]);
  useEffect(() => { const subscription = AppState.addEventListener("change", (state) => { if (state === "active") void sync(); }); return () => subscription.remove(); }, [sync]);
  useEffect(() => { if (snapshot.status !== "connected") return; let remove: (() => void) | undefined; void startHealthObservers(userKey, preferences, () => { void sync(); }).then((cleanup) => { remove = cleanup; }); return () => remove?.(); }, [preferences, snapshot.status, sync, userKey]);

  const toggle = (key: HealthCategory) => { const next = { ...preferences, [key]: !preferences[key] }; setPreferences(next); void saveHealthPreferences(userKey, next); };
  const applyPermissions = async () => { setBusy(true); const result = await requestHealthAuthorization(userKey, preferences); setSnapshot(result); if (result.status === "syncing") await sync(preferences); setBusy(false); };
  const confirmDisconnect = () => Alert.alert("Disconnect Apple Health?", "This removes PulseCoach’s local connection, observers, anchors, and cached summaries. It does not revoke Apple Health permissions.", [{ text: "Cancel", style: "cancel" }, { text: "Disconnect", style: "destructive", onPress: async () => { await disconnectHealth(userKey); setSnapshot(blank()); setPreferences(DEFAULT_HEALTH_PREFERENCES); } }]);
  const confirmDelete = () => Alert.alert("Delete cached health data?", "This deletes only PulseCoach’s local imported summaries, anchors, and cached samples. Original Apple Health records and permissions remain unchanged.", [{ text: "Cancel", style: "cancel" }, { text: "Delete cache", style: "destructive", onPress: async () => { await deleteImportedHealthData(userKey); setSnapshot(await loadHealthSnapshot(userKey)); } }]);

  const history = useMemo(() => snapshot.stepsHistory ?? [], [snapshot.stepsHistory]); const max = useMemo(() => Math.max(...history.map((item) => item.value), 1), [history]); const summary = snapshot.summary;
  const status = { not_setup: "Not set up", permission_required: "Permission required", connected: "Connected", syncing: "Syncing", sync_failed: "Sync failed" }[snapshot.status];

  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void sync()} tintColor={mint}/>}>
    <Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><View style={styles.icon}><IconSymbol name="heart.text.square.fill" size={34} color={mint}/></View><Text style={styles.eyebrow}>PROFILE · SETTINGS</Text><Text style={styles.title}>Apple Health</Text><Text style={styles.copy}>Manage the health categories PulseCoach can read, connection status, syncing, permissions, and diagnostics. Apple controls permissions and may not directly disclose whether read access was denied.</Text>
    <Text style={styles.section}>Health categories</Text><View style={styles.card}>{(Object.keys(HEALTH_CATEGORIES) as HealthCategory[]).map((key) => <Pressable key={key} onPress={() => toggle(key)} style={({ pressed }) => [styles.category, pressed && styles.pressed]}><View style={styles.flex}><Text style={styles.categoryTitle}>{HEALTH_CATEGORIES[key].label}</Text>{key === "sleep" ? <Text style={styles.small}>Optional and off by default</Text> : null}</View><Text style={[styles.toggle, preferences[key] && styles.toggleOn]}>{preferences[key] ? "ON" : "OFF"}</Text></Pressable>)}<Pressable onPress={applyPermissions} disabled={busy} style={({ pressed }) => [styles.apply, pressed && styles.pressed]}><Text style={styles.applyText}>{busy ? "Requesting…" : snapshot.status === "connected" ? "Apply permission choices" : "Request selected categories"}</Text></Pressable></View>
    <View style={styles.card}><View style={styles.statusRow}><View style={[styles.dot, snapshot.status === "connected" && styles.dotOn]}/><View style={styles.flex}><Text style={styles.cardTitle}>{status}</Text><Text style={styles.small}>{snapshot.errorMessage ?? (snapshot.lastSyncedAt ? `Last synced ${new Date(snapshot.lastSyncedAt).toLocaleString("en-AU")}` : "No successful sync yet")}</Text></View></View><View style={styles.actions}><Pressable onPress={() => void sync()} style={styles.secondary}><Text style={styles.secondaryText}>{refreshing ? "Syncing…" : "Sync now"}</Text></Pressable><Pressable onPress={() => void Linking.openSettings()} style={styles.secondary}><Text style={styles.secondaryText}>iPhone settings</Text></Pressable></View></View>
    <View style={styles.hero}><Text style={styles.label}>TODAY’S STEPS</Text><Text style={styles.value}>{summary?.steps === undefined ? "No data" : Math.round(summary.steps).toLocaleString("en-AU")}</Text><Text style={styles.small}>Local-day total after UUID/source deduplication.</Text></View>
    <View style={styles.grid}><Metric label="Distance" value={summary?.distanceMeters === undefined ? "No data" : `${(summary.distanceMeters / 1000).toFixed(1)} km`}/><Metric label="Active energy" value={summary?.activeEnergyKcal === undefined ? "No data" : `${Math.round(summary.activeEnergyKcal)} kcal`}/><Metric label="Exercise" value={summary?.exerciseMinutes === undefined ? "No data" : `${Math.round(summary.exerciseMinutes)} min`}/><Metric label="Heart rate" value={summary?.heartRateAverage === undefined ? "No data" : `${Math.round(summary.heartRateAverage)} bpm`}/><Metric label="Weight" value={summary?.weightKg === undefined ? "No data" : `${summary.weightKg.toFixed(1)} kg`}/><Metric label="Sleep" value={summary?.sleepMinutes === undefined ? "Not enabled/no data" : `${Math.round(summary.sleepMinutes)} min`}/></View>
    <Pressable onPress={() => router.push("/health-diagnostics" as never)}><Text style={styles.link}>Open sync diagnostics ›</Text></Pressable><Text style={styles.section}>Steps · last 30 days</Text>{history.length ? <View style={styles.card}><View style={styles.chart}>{history.map((item) => <View key={item.start.toString()} style={[styles.bar, { height: Math.max(4, item.value / max * 100) }]}/>)}</View></View> : <Text style={styles.copy}>No history is available until a successful sync completes.</Text>}
    <View style={styles.notice}><Text style={styles.cardTitle}>Privacy and revocation</Text><Text style={styles.copy}>Snapshots are stored under the signed-in user and are not sent to AI Coach. Disconnecting here affects only PulseCoach. Revoke Apple permissions in iPhone Settings › Health › Data Access & Devices › PulseCoach.</Text></View><View style={styles.dangerRow}><Pressable onPress={confirmDisconnect}><Text style={styles.danger}>Disconnect integration</Text></Pressable><Pressable onPress={confirmDelete}><Text style={styles.danger}>Delete cached data</Text></Pressable></View>
  </ScrollView></ScreenContainer>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.label}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 32, gap: 15 }, flex: { flex: 1 }, pressed: { opacity: 0.72 }, back: { color: mint, fontWeight: "800" }, icon: { width: 70, height: 70, borderRadius: 23, backgroundColor: "#202A21", alignItems: "center", justifyContent: "center" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 29, lineHeight: 35, fontWeight: "900" }, copy: { color: muted, fontSize: 12, lineHeight: 18 }, section: { color: "#F4F7F0", fontSize: 18, fontWeight: "900", marginTop: 4 }, card: { backgroundColor: "#1B231D", borderRadius: 18, padding: 15, borderWidth: 1, borderColor: "#2D392E", gap: 10 }, category: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#263128" }, categoryTitle: { color: "#F4F7F0", fontWeight: "800", fontSize: 13 }, small: { color: muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, toggle: { color: muted, fontSize: 11, fontWeight: "900", backgroundColor: "#303A31", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10 }, toggleOn: { backgroundColor: mint, color: "#111513" }, apply: { backgroundColor: "#2B3B27", borderRadius: 13, padding: 13, alignItems: "center", borderWidth: 1, borderColor: "#4D653D", marginTop: 8 }, applyText: { color: mint, fontWeight: "900", fontSize: 12 }, statusRow: { flexDirection: "row", alignItems: "center", gap: 10 }, dot: { width: 11, height: 11, borderRadius: 6, backgroundColor: "#8A6F39" }, dotOn: { backgroundColor: mint }, cardTitle: { color: "#F4F7F0", fontWeight: "900", fontSize: 15 }, actions: { flexDirection: "row", gap: 8 }, secondary: { flex: 1, backgroundColor: "#2B3B27", padding: 11, borderRadius: 12, alignItems: "center" }, secondaryText: { color: mint, fontWeight: "800", fontSize: 12 }, hero: { backgroundColor: "#202A21", borderRadius: 20, padding: 18, borderWidth: 1, borderColor: "#354536" }, label: { color: muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, value: { color: mint, fontSize: 39, lineHeight: 45, fontWeight: "900", marginTop: 5 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, metric: { width: "48%", minHeight: 80, backgroundColor: "#1B231D", borderRadius: 15, padding: 12, borderWidth: 1, borderColor: "#263128" }, metricValue: { color: "#F4F7F0", fontSize: 16, fontWeight: "900", marginTop: 8 }, link: { color: mint, fontWeight: "900", fontSize: 12 }, chart: { height: 108, flexDirection: "row", alignItems: "flex-end", gap: 2 }, bar: { flex: 1, minWidth: 2, backgroundColor: mint, borderTopLeftRadius: 2, borderTopRightRadius: 2 }, notice: { backgroundColor: "#202A21", borderRadius: 17, padding: 15, borderWidth: 1, borderColor: "#354536" }, dangerRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4 }, danger: { color: "#F49AB5", fontSize: 12, fontWeight: "900" } });
