import { useCallback, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import Swipeable from "react-native-gesture-handler/ReanimatedSwipeable";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { deleteMovementLimitation, loadMovementLimitations, saveMovementLimitation, type MovementLimitation } from "@/lib/movement-limitations";
const mint = "#B8F36B"; const muted = "#A8B3A6";
const storageKey = (user: { openId?: string; id?: number } | null) => user?.openId ?? (user?.id ? String(user.id) : "local-user");
export default function InjuriesScreen() {
  const { user } = useAuth({ autoFetch: false });
  const userKey = storageKey(user);
  const [area, setArea] = useState("");
  const [notes, setNotes] = useState("");
  const [limitations, setLimitations] = useState<MovementLimitation[]>([]);
  useFocusEffect(useCallback(() => { let active = true; void loadMovementLimitations(userKey).then((items) => { if (active) setLimitations(items); }); return () => { active = false; }; }, [userKey]));
  const save = async () => { if (!area.trim()) return; setLimitations(await saveMovementLimitation(userKey, area, notes)); setArea(""); setNotes(""); };
  const remove = async (id: string) => setLimitations(await deleteMovementLimitation(userKey, id));
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.eyebrow}>LIMITATIONS</Text><Text style={styles.title}>Train around what matters.</Text><Text style={styles.subtitle}>Save each pain area or movement limitation separately. PulseCoach will keep exercises visible and warn you when one may heavily involve an affected area.</Text><View style={styles.warning}><Text style={styles.warningTitle}>Not a diagnosis</Text><Text style={styles.warningCopy}>PulseCoach can highlight exercises for extra care, but cannot decide whether an exercise is safe for you. Stop if symptoms worsen and seek qualified advice for persistent, severe, or new pain.</Text></View>{limitations.length ? <><Text style={styles.section}>Saved limitations</Text><Text style={styles.swipeHint}>Swipe a card left to delete it when it is no longer an issue.</Text>{limitations.map((item) => <Swipeable key={item.id} overshootRight={false} renderRightActions={() => <Pressable style={styles.deleteAction} onPress={() => void remove(item.id)}><Text style={styles.deleteText}>Delete</Text></Pressable>}><View style={styles.limitationCard}><Text style={styles.limitationTitle}>{item.area}</Text>{item.notes ? <Text style={styles.limitationNotes}>{item.notes}</Text> : null}</View></Swipeable>)}</> : null}<Text style={styles.section}>Add a limitation</Text><View style={styles.card}><TextInput value={area} onChangeText={setArea} placeholder="e.g. right shoulder pain" placeholderTextColor="#718071" style={styles.input} /><TextInput value={notes} onChangeText={setNotes} placeholder="Optional — movements or details to remember" placeholderTextColor="#718071" style={[styles.input, styles.multiline]} multiline /><Pressable disabled={!area.trim()} style={[styles.button, !area.trim() && styles.buttonDisabled]} onPress={() => void save()}><Text style={styles.buttonText}>Save limitation</Text></Pressable></View><Text style={styles.section}>Movement reminders</Text>{["Keep two reps in reserve while testing a modification.", "Use a stable, controlled range rather than forcing depth.", "Replace an exercise if you cannot maintain comfortable technique.", "Warm up gradually and cool down with gentle mobility."].map((text) => <View style={styles.row} key={text}><Text style={styles.bullet}>•</Text><Text style={styles.rowText}>{text}</Text></View>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, warning: { backgroundColor: "#2A241A", borderRadius: 18, padding: 15, borderWidth: 1, borderColor: "#57482D", marginTop: 5 }, warningTitle: { color: "#F7CF77", fontSize: 13, fontWeight: "800" }, warningCopy: { color: "#D4C39D", fontSize: 11, lineHeight: 16, marginTop: 5 }, section: { color: "#F4F7F0", fontSize: 18, fontWeight: "800", marginTop: 3 }, swipeHint: { color: muted, fontSize: 11 }, limitationCard: { backgroundColor: "#202A21", borderRadius: 17, padding: 15, borderWidth: 1, borderColor: "#354536", minHeight: 68, justifyContent: "center" }, limitationTitle: { color: "#F4F7F0", fontSize: 15, fontWeight: "800" }, limitationNotes: { color: muted, fontSize: 11, lineHeight: 16, marginTop: 5 }, deleteAction: { width: 88, marginLeft: 8, borderRadius: 17, backgroundColor: "#9D3C3C", alignItems: "center", justifyContent: "center" }, deleteText: { color: "white", fontWeight: "800" }, card: { backgroundColor: "#1B231D", borderRadius: 19, padding: 14, gap: 10, borderWidth: 1, borderColor: "#2D392E" }, input: { backgroundColor: "#111513", color: "#F4F7F0", borderRadius: 12, padding: 13, borderWidth: 1, borderColor: "#2D392E" }, multiline: { minHeight: 78, textAlignVertical: "top" }, button: { backgroundColor: mint, borderRadius: 13, padding: 14, alignItems: "center" }, buttonDisabled: { opacity: 0.45 }, buttonText: { color: "#111513", fontWeight: "800" }, row: { flexDirection: "row", gap: 10, alignItems: "flex-start", paddingVertical: 4 }, bullet: { color: mint, fontSize: 18, lineHeight: 17 }, rowText: { color: muted, fontSize: 13, lineHeight: 19, flex: 1 }
});
