import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
const mint = "#B8F36B"; const muted = "#A8B3A6";
export default function LogScreen() { const [saved, setSaved] = useState(false); const [weight, setWeight] = useState(32); return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.eyebrow}>LOG SESSION</Text><Text style={styles.title}>Seated row machine</Text><Text style={styles.subtitle}>Record what you actually did. PulseCoach can use this as a reference next time.</Text><View style={styles.last}><View><Text style={styles.lastLabel}>LAST LOGGED</Text><Text style={styles.lastValue}>28 kg · 3 × 10</Text><Text style={styles.lastMeta}>12 days ago</Text></View><IconSymbol name="clock.arrow.circlepath" size={25} color={mint} /></View><Field label="Weight (kg)" value={String(weight)} onChange={(text) => setWeight(Number(text) || 0)} /><View style={styles.two}><Field label="Sets" value="3" onChange={() => {}} /><Field label="Reps" value="10" onChange={() => {}} /></View><View style={styles.tip}><Text style={styles.tipTitle}>Next time</Text><Text style={styles.tipCopy}>{weight >= 28 ? "If all reps felt controlled, try 30–32 kg next session. Keep form quality ahead of the number." : "Aim to match your last controlled session before increasing the load."}</Text></View><Pressable style={styles.save} onPress={() => setSaved(true)}><IconSymbol name="checkmark" size={18} color="#111513" /><Text style={styles.saveText}>{saved ? "Saved to workout history" : "Save exercise log"}</Text></Pressable><Pressable style={styles.secondary} onPress={() => router.push("/machine" as any)}><IconSymbol name="camera.fill" size={18} color={mint} /><Text style={styles.secondaryText}>Scan another machine</Text></Pressable><Text style={styles.note}>Progress suggestions are conservative prompts, not requirements. Reduce the load or stop if technique breaks down or you feel pain.</Text></ScrollView></ScreenContainer>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType="decimal-pad" style={styles.input} /></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, last: { backgroundColor: "#202A21", borderRadius: 19, padding: 17, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1, borderColor: "#354536", marginTop: 5 }, lastLabel: { color: mint, fontSize: 10, fontWeight: "800", letterSpacing: 1.2 }, lastValue: { color: "#F4F7F0", fontSize: 19, fontWeight: "800", marginTop: 6 }, lastMeta: { color: muted, fontSize: 12, marginTop: 3 }, two: { flexDirection: "row", gap: 10 }, field: { flex: 1, gap: 7 }, fieldLabel: { color: "#DCE5D8", fontSize: 13, fontWeight: "700" }, input: { backgroundColor: "#1B231D", color: "#F4F7F0", borderRadius: 14, borderWidth: 1, borderColor: "#2D392E", padding: 14, fontSize: 17, fontWeight: "800" }, tip: { backgroundColor: "#1B231D", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#263128" }, tipTitle: { color: mint, fontWeight: "800", fontSize: 14 }, tipCopy: { color: muted, fontSize: 13, lineHeight: 19, marginTop: 5 }, save: { backgroundColor: mint, borderRadius: 16, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, saveText: { color: "#111513", fontWeight: "800", fontSize: 14 }, secondary: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, padding: 10 }, secondaryText: { color: mint, fontWeight: "800" }, note: { color: "#718071", fontSize: 11, lineHeight: 16, textAlign: "center" }
});
