import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { startOAuthLogin } from "@/constants/oauth";
import { ScreenContainer } from "@/components/screen-container";
const mint = "#B8F36B"; const muted = "#A8B3A6";
export default function LoginScreen() { const [loading, setLoading] = useState(""); const signIn = async (provider: string) => { setLoading(provider); await startOAuthLogin(); setLoading(""); }; return <ScreenContainer className="px-6"><View style={styles.content}><View style={styles.logo}><Text style={styles.logoText}>⌁</Text></View><Text style={styles.eyebrow}>VELTURA</Text><Text style={styles.title}>Your training, nutrition, and momentum in one place.</Text><Text style={styles.copy}>Sign in to keep your plans, progress, health permissions, and friend settings connected across sessions.</Text><Pressable style={styles.primary} onPress={() => router.push("/account" as any)}><Text style={styles.primaryText}>Create an account</Text></Pressable><Text style={styles.or}>Already have an account?</Text><View style={styles.providers}><Provider label="Continue with Apple" icon="" onPress={() => signIn("Apple")} loading={loading === "Apple"} /><Provider label="Continue with Google" icon="G" onPress={() => signIn("Google")} loading={loading === "Google"} /><Provider label="Continue with Facebook" icon="f" onPress={() => signIn("Facebook")} loading={loading === "Facebook"} /></View><Pressable style={styles.email} onPress={() => router.push("/account" as any)}><Text style={styles.emailText}>Sign in with email and password</Text></Pressable><Text style={styles.privacy}>Your account keeps your data separated from other users. You control health permissions, sharing, and deletion.</Text></View></ScreenContainer>; }
function Provider({ label, icon, onPress, loading }: { label: string; icon: string; onPress: () => void; loading: boolean }) { return <Pressable style={({ pressed }) => [styles.provider, pressed && styles.pressed]} onPress={onPress}><Text style={styles.providerIcon}>{icon}</Text><Text style={styles.providerText}>{loading ? "Opening sign in…" : label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { flex: 1, justifyContent: "center", gap: 13 }, logo: { width: 64, height: 64, borderRadius: 21, backgroundColor: "#2B3B27", alignItems: "center", justifyContent: "center", marginBottom: 6 }, logoText: { color: mint, fontSize: 43 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.7 }, title: { color: "#F4F7F0", fontSize: 31, lineHeight: 37, fontWeight: "900", letterSpacing: -1 }, copy: { color: muted, fontSize: 14, lineHeight: 20 }, primary: { backgroundColor: mint, borderRadius: 15, padding: 16, alignItems: "center", marginTop: 6 }, primaryText: { color: "#111513", fontSize: 15, fontWeight: "900" }, or: { color: muted, fontSize: 12, textAlign: "center", marginTop: 2 }, providers: { gap: 8 }, provider: { backgroundColor: "#1B231D", borderRadius: 14, borderWidth: 1, borderColor: "#2D392E", padding: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, providerIcon: { color: "#F4F7F0", fontSize: 17, fontWeight: "900", width: 20, textAlign: "center" }, providerText: { color: "#F4F7F0", fontSize: 13, fontWeight: "800" }, email: { alignItems: "center", padding: 10 }, emailText: { color: mint, fontSize: 12, fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] }, privacy: { color: "#718071", fontSize: 10, lineHeight: 15, marginTop: 3 }
});
