import { useRef, useState } from "react";
import { CameraView, useCameraPermissions } from "expo-camera";
import { router, useLocalSearchParams } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { KINGS_GYM_GLEN_INNES, LocalGymRepository, MockEquipmentRecognizer, GENERIC_EQUIPMENT_CATALOGUE, chooseRecognitionCandidates, type EquipmentRecognitionResult, type GymEquipmentInstance } from "@/lib/gym-directory";

const mint = "#B8F36B"; const muted = "#A8B3A6"; const repository = new LocalGymRepository(); const recognizer = new MockEquipmentRecognizer();

export default function MachineScannerScreen() {
  const params = useLocalSearchParams<{ gymId?: string }>();
  const insets = useSafeAreaInsets();
  const [permission, requestPermission] = useCameraPermissions();
  const cameraRef = useRef<CameraView>(null); const recognitionRun = useRef(0);
  const [photoUri, setPhotoUri] = useState<string>(); const [results, setResults] = useState<EquipmentRecognitionResult[]>([]); const [selected, setSelected] = useState<EquipmentRecognitionResult>(); const [manual, setManual] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [cameraError, setCameraError] = useState<string>();
  const gymId = params.gymId ?? KINGS_GYM_GLEN_INNES.id;
  const close = () => { recognitionRun.current += 1; setBusy(false); setPhotoUri(undefined); setResults([]); setSelected(undefined); if (router.canDismiss()) router.dismiss(); else if (router.canGoBack()) router.back(); else router.replace("/gym" as any); };
  const closeButton = <Pressable accessibilityRole="button" accessibilityLabel="Close machine identification" hitSlop={6} style={[styles.closeButton, { top: insets.top + 10 }]} onPress={close}><Text style={styles.closeIcon}>‹</Text></Pressable>;
  const capture = async () => { const run = ++recognitionRun.current; setBusy(true); setMessage(""); const photo = await cameraRef.current?.takePictureAsync({ quality: 0.6, skipProcessing: false }); if (run !== recognitionRun.current) return; if (!photo?.uri) { setMessage("The photo was not captured. Check camera access and try again."); setBusy(false); return; } setPhotoUri(photo.uri); const confirmed = await repository.listEquipment(gymId); const raw = await recognizer.recognize({ imageDataUrl: photo.uri, gymId, capturedAt: new Date().toISOString() }, GENERIC_EQUIPMENT_CATALOGUE, confirmed); if (run !== recognitionRun.current) return; setResults(chooseRecognitionCandidates(raw, confirmed, GENERIC_EQUIPMENT_CATALOGUE)); setBusy(false); };
  const save = async () => { if (!selected) return; const generic = GENERIC_EQUIPMENT_CATALOGUE.find((item) => item.id === selected.genericEquipmentTypeId); if (!generic) return; const instanceId = selected.possibleGymEquipmentInstanceId ?? `equipment-${Date.now()}`; const instance: GymEquipmentInstance = { id: instanceId, gymId, genericEquipmentTypeId: generic.id, brandModel: selected.brand || selected.model ? { manufacturer: selected.brand ?? "Unknown", model: selected.model } : undefined, unit: "kilograms", compatibleExerciseIds: selected.compatibleExerciseIds, primaryMuscles: selected.primaryMuscles, secondaryMuscles: selected.secondaryMuscles, setupInstructions: generic.setupInstructions, movementInstructions: generic.movementInstructions, safetyGuidance: generic.safetyGuidance, approvedExerciseIds: selected.compatibleExerciseIds, videoExerciseIds: [], photoIds: photoUri ? [`photo-${Date.now()}`] : [], availability: "Unknown", verificationStatus: "Unverified", confirmationCount: 0, createdAt: new Date().toISOString() }; await repository.saveEquipment(instance); setMessage("Saved as an unverified gym listing. Please confirm the machine label and availability."); };
  const filteredManual = manual ? GENERIC_EQUIPMENT_CATALOGUE.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(manual.toLowerCase())) : [];
  const manualPanel = <><Text style={styles.section}>MANUAL EQUIPMENT SEARCH</Text><TextInput value={manual} onChangeText={setManual} placeholder="Search equipment type" placeholderTextColor="#718071" style={styles.input} />{filteredManual.map((item) => <Pressable key={item.id} style={styles.result} onPress={() => { setSelected({ genericEquipmentTypeId: item.id, confidence: 1, evidence: ["Manual selection"], compatibleExerciseIds: item.compatibleExerciseIds, primaryMuscles: item.primaryMuscles, secondaryMuscles: item.secondaryMuscles, recognitionSource: "mock", requiresConfirmation: true }); setMessage("Manual correction selected. Confirm before saving."); }}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.cardCopy}>{item.category}</Text></Pressable>)}<Pressable style={styles.button} disabled={!selected} onPress={() => void save()}><Text style={styles.buttonText}>Confirm and save at this gym</Text></Pressable>{message ? <Text style={styles.warning}>{message}</Text> : null}</>;
  if (!permission) return <ScreenContainer><View style={styles.screen}>{closeButton}<View style={styles.center}><Text style={styles.title}>Preparing camera…</Text></View></View></ScreenContainer>;
  if (!permission.granted) return <ScreenContainer><View style={styles.screen}>{closeButton}<ScrollView contentContainerStyle={styles.content}><View style={styles.center}><Text style={styles.eyebrow}>MACHINE SCANNER</Text><Text style={styles.title}>Camera access is optional.</Text><Text style={styles.subtitle}>Camera access is needed to identify a machine. Try again, open Settings, or continue manually.</Text><Pressable style={styles.button} onPress={() => void requestPermission()}><Text style={styles.buttonText}>Try Again</Text></Pressable><Pressable style={styles.secondary} onPress={() => void Linking.openSettings()}><Text style={styles.secondaryText}>Open Settings</Text></Pressable>{manualPanel}</View></ScrollView></View></ScreenContainer>;
  return <ScreenContainer><View style={styles.screen}>{closeButton}<ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>MACHINE SCANNER</Text><Text style={styles.title}>Photograph the whole machine.</Text><Text style={styles.subtitle}>Include the console, seat, handles, cables, weight stack and identifying label.</Text>{!results.length ? <><View style={styles.camera}>{cameraError ? <View style={styles.cameraFailure}><Text style={styles.cardTitle}>Camera could not start</Text><Text style={styles.cardCopy}>{cameraError}</Text><Pressable style={styles.button} onPress={() => setCameraError(undefined)}><Text style={styles.buttonText}>Retry camera</Text></Pressable></View> : <CameraView ref={cameraRef} style={StyleSheet.absoluteFillObject} facing="back" onCameraReady={() => setCameraError(undefined)} onMountError={(event) => setCameraError(event.message || "Camera permission or hardware is unavailable.")} />}{!cameraError ? <View style={styles.target}><Text style={styles.targetText}>Full machine in frame</Text></View> : null}</View><Pressable style={styles.button} disabled={busy || Boolean(cameraError)} onPress={() => void capture()}><Text style={styles.buttonText}>{busy ? "Examining photo…" : photoUri ? "Retake photo" : "Capture photo"}</Text></Pressable></> : <><Text style={styles.section}>TOP MATCHES</Text>{results.map((result, index) => <Pressable key={`${result.genericEquipmentTypeId}-${index}`} style={styles.result} onPress={() => setSelected(result)}><Text style={styles.cardTitle}>{GENERIC_EQUIPMENT_CATALOGUE.find((item) => item.id === result.genericEquipmentTypeId)?.name ?? "Unknown equipment"}</Text><Text style={styles.cardCopy}>{Math.round(result.confidence * 100)}% confidence · confirmation required</Text></Pressable>)}<Pressable style={styles.button} disabled={!selected} onPress={() => void save()}><Text style={styles.buttonText}>Confirm and save at this gym</Text></Pressable></>}{manualPanel}</ScrollView></View></ScreenContainer>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { gap: 12, paddingBottom: 35 }, center: { flex: 1, justifyContent: "center", gap: 14 }, closeButton: { position: "absolute", left: 16, zIndex: 20, elevation: 20, width: 48, height: 48, borderRadius: 24, backgroundColor: "rgba(6,32,51,.92)", borderWidth: 1, borderColor: mint, alignItems: "center", justifyContent: "center" }, closeIcon: { color: "#FFFFFF", fontSize: 32 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900" }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "900" }, subtitle: { color: muted, lineHeight: 19 }, camera: { height: 390, overflow: "hidden", borderRadius: 22, borderWidth: 2, borderColor: "#87C7E8", backgroundColor: "#263128" }, cameraFailure: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 20 }, target: { ...StyleSheet.absoluteFillObject, margin: 18, borderWidth: 1, borderColor: mint, borderRadius: 18, alignItems: "center", justifyContent: "flex-end", paddingBottom: 14 }, targetText: { color: "#F4F7F0", backgroundColor: "#102333CC", padding: 9 }, button: { backgroundColor: mint, borderRadius: 15, padding: 15, alignItems: "center" }, buttonText: { color: "#10202A", fontWeight: "900" }, secondary: { backgroundColor: "rgba(6,32,51,.8)", borderColor: mint, borderWidth: 1, borderRadius: 15, padding: 15, alignItems: "center" }, secondaryText: { color: mint, fontWeight: "900" }, section: { color: mint, fontWeight: "900", marginTop: 9 }, result: { padding: 14, borderRadius: 15, backgroundColor: "rgba(66,132,174,.38)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)" }, cardTitle: { color: "#F4F7F0", fontWeight: "900" }, cardCopy: { color: muted, fontSize: 11 }, input: { backgroundColor: "rgba(10,43,67,.5)", borderWidth: 1, borderColor: "rgba(174,224,255,.46)", borderRadius: 13, padding: 13, color: "#F4F7F0" }, warning: { color: "#F7CF77" } });
