import { useRef, useState } from "react";
import { CameraView, useCameraPermissions } from "expo-camera";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { trpc } from "@/lib/trpc";
const mint = "#B8F36B"; const muted = "#A8B3A6";
type MachineResult = { name: string; category: string; confidence: number; primaryMuscles: string[]; setup: string; formCues: string[]; suggestedTracking: string[]; alternatives: string[]; needsConfirmation: boolean };
export default function MachineScreen() {
  const [permission, requestPermission] = useCameraPermissions(); const cameraRef = useRef<CameraView>(null); const [result, setResult] = useState<MachineResult>(); const [message, setMessage] = useState("");
  const analysis = trpc.scan.machine.useMutation({ onSuccess: (data) => { setResult(data); setMessage(""); }, onError: () => setMessage("VELTURA could not identify this photo. Try a wider view in good light with the console, pedals, handles, cables or weight stack visible.") });
  const capture = async () => { const photo = await cameraRef.current?.takePictureAsync({ quality: 0.5, base64: true, skipProcessing: false }); if (!photo?.base64) { setMessage("The photo was not captured. Try again."); return; } setMessage("Examining the whole machine…"); analysis.mutate({ imageDataUrl: `data:image/jpeg;base64,${photo.base64}` }); };
  if (!permission) return null;
  if (!permission.granted) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5 pt-4"><View style={styles.permission}><View style={styles.bigIcon}><IconSymbol name="camera.fill" size={32} color={mint} /></View><Text style={styles.title}>Identify a machine</Text><Text style={styles.subtitle}>Take a full photo and VELTURA will identify strength machines, treadmills, bikes, rowers, ellipticals and stair climbers.</Text><Pressable style={styles.button} onPress={requestPermission}><Text style={styles.buttonText}>Allow camera access</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable>{!result ? <><Text style={styles.eyebrow}>AI MACHINE SCAN</Text><Text style={styles.title}>Fit the whole machine in view.</Text><Text style={styles.subtitle}>For cardio equipment, include the console, seat, pedals and handles. For weights, include the seat, cables or weight stack and any name label.</Text><View style={styles.cameraFrame}><CameraView ref={cameraRef} style={StyleSheet.absoluteFillObject} facing="back" /><View style={styles.target}><Text style={styles.targetText}>Step back and include the entire machine</Text></View></View><Pressable style={styles.capture} onPress={() => void capture()} disabled={analysis.isPending}><View style={styles.shutter}><View style={styles.shutterInner} /></View><Text style={styles.captureText}>{analysis.isPending ? "Identifying…" : "Take photo"}</Text></Pressable>{message ? <Text style={styles.warning}>{message}</Text> : null}</> : <><Text style={styles.eyebrow}>BEST MATCH · {Math.round(result.confidence)}%</Text><Text style={styles.title}>{result.name}</Text><Text style={styles.subtitle}>{result.category}{result.needsConfirmation ? " · Please confirm using the machine label" : " · High-confidence visual match"}</Text><View style={styles.result}><Label title="PRIMARY MUSCLES" value={result.primaryMuscles.join(" · ") || "Full-body/cardio effort"} /><Label title="SETUP" value={result.setup} /><Label title="FORM CUES" value={result.formCues.join(" • ")} /><Label title="TRACK" value={result.suggestedTracking.join(" · ")} />{result.alternatives.length ? <Label title="OTHER POSSIBLE MATCHES" value={result.alternatives.join(" · ")} /> : null}</View><Pressable style={styles.button} onPress={() => { const cardio = /bike|row|treadmill|elliptical|stair/i.test(result.name); if (cardio) router.push("/gym" as any); else router.push({ pathname: "/workout", params: { focus: "Full body", equipment: "Full gym", fresh: "1" } } as any); }}><Text style={styles.buttonText}>Use this equipment</Text></Pressable><Pressable style={styles.secondary} onPress={() => { setResult(undefined); setMessage(""); }}><Text style={styles.secondaryText}>Scan again</Text></Pressable><Text style={styles.note}>Visual identification is a best match, not a guarantee. Confirm the printed machine name and ask gym staff if setup is unfamiliar.</Text></>}</ScrollView></ScreenContainer>;
}
function Label({ title, value }: { title: string; value: string }) { return <View><Text style={styles.resultLabel}>{title}</Text><Text style={styles.resultCopy}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, permission: { flex: 1, justifyContent: "center", alignItems: "center", gap: 16, padding: 20 }, bigIcon: { width: 72, height: 72, borderRadius: 24, backgroundColor: "#264F6D", alignItems: "center", justifyContent: "center" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, back: { color: mint, fontSize: 15, fontWeight: "800" }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "900" }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, cameraFrame: { height: 390, borderRadius: 24, overflow: "hidden", backgroundColor: "#263128", borderWidth: 2, borderColor: "#87C7E8" }, target: { position: "absolute", top: 18, left: 18, right: 18, bottom: 18, borderWidth: 1, borderColor: "#B8F36B", borderRadius: 18, alignItems: "center", justifyContent: "flex-end", paddingBottom: 15 }, targetText: { color: "#F4F7F0", fontSize: 11, fontWeight: "800", backgroundColor: "#102333CC", padding: 9, borderRadius: 9 }, capture: { alignItems: "center", gap: 8 }, shutter: { width: 72, height: 72, borderRadius: 36, borderWidth: 5, borderColor: mint, alignItems: "center", justifyContent: "center" }, shutterInner: { width: 54, height: 54, borderRadius: 27, backgroundColor: mint }, captureText: { color: "#F4F7F0", fontWeight: "900" }, result: { backgroundColor: "rgba(40, 80, 110, 0.82)", borderRadius: 20, padding: 17, gap: 14, borderWidth: 1, borderColor: "#87C7E8" }, resultLabel: { color: mint, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 4 }, resultCopy: { color: "#E6F3F8", fontSize: 13, lineHeight: 19 }, button: { backgroundColor: mint, borderRadius: 16, padding: 16, alignItems: "center" }, buttonText: { color: "#111513", fontSize: 15, fontWeight: "900" }, secondary: { alignItems: "center", padding: 10 }, secondaryText: { color: mint, fontWeight: "900" }, warning: { color: "#F7CF77", textAlign: "center", lineHeight: 18 }, note: { color: "#8DA4AF", fontSize: 11, lineHeight: 16, textAlign: "center" } });
