import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";
const mint = "#B8F36B"; const muted = "#A8B3A6";
export default function ProfileScreen() { const [feedback, setFeedback] = useState(""); const [sent, setSent] = useState(false); const feedbackMutation = trpc.feedback.create.useMutation({ onSuccess: () => { setSent(true); setFeedback(""); } }); return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Text onPress={() => router.back()} style={styles.back}>‹  Back</Text><Text style={styles.eyebrow}>YOUR PROFILE</Text><Text style={styles.title}>Make coaching fit you.</Text><Text style={styles.subtitle}>These preferences stay on this device in the first prototype and help PulseCoach avoid generic suggestions.</Text><Group title="Primary goal" items={["Build strength", "Improve fitness", "Maintain health"]} /><Group title="Food preferences" items={["No preference", "Vegetarian", "High-protein"]} /><Group title="Training setup" items={["Dumbbells", "Full gym", "Bodyweight"]} /><Group title="Coaching style" items={["Encouraging", "Direct", "Minimal"]} /><Text style={styles.note}>Add allergies, injuries, or medical restrictions before asking for personalized food or exercise suggestions. When in doubt, speak with a qualified professional.</Text><View style={styles.feedback}><Text style={styles.feedbackTitle}>Help shape PulseCoach</Text><Text style={styles.feedbackCopy}>Suggest a feature, report an issue, or tell us what would make coaching more useful.</Text><TextInput value={feedback} onChangeText={setFeedback} placeholder="Your idea or issue…" placeholderTextColor="#718071" multiline style={styles.feedbackInput} /><Pressable style={styles.feedbackButton} onPress={() => { if (feedback.trim()) feedbackMutation.mutate({ category: "feature", message: feedback.trim(), contactAllowed: false }); }}><Text style={styles.feedbackButtonText}>{feedbackMutation.isPending ? "Sending…" : sent ? "Thanks — feedback received" : "Send feedback"}</Text></Pressable></View><Pressable style={styles.adminLink} onPress={() => router.push("/admin" as any)}><Text style={styles.adminText}>Owner administration ›</Text></Pressable></ScrollView></ScreenContainer>; }
function Group({ title, items }: { title: string; items: string[] }) { return <View style={styles.group}><Text style={styles.groupTitle}>{title}</Text><View style={styles.chips}>{items.map((item, i) => <View key={item} style={[styles.chip, i === 0 && styles.chipActive]}><Text style={[styles.chipText, i === 0 && styles.chipTextActive]}>{item}</Text></View>)}</View></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 18 }, back: { color: mint, fontSize: 15, fontWeight: "700", marginBottom: 8 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, group: { gap: 10, marginTop: 4 }, groupTitle: { color: "#F4F7F0", fontSize: 16, fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, chip: { paddingVertical: 11, paddingHorizontal: 14, borderRadius: 14, backgroundColor: "#1B231D", borderWidth: 1, borderColor: "#2D392E" }, chipActive: { backgroundColor: "#2C3B25", borderColor: mint }, chipText: { color: muted, fontSize: 13, fontWeight: "700" }, chipTextActive: { color: mint }, feedback: { backgroundColor: "#202A21", borderRadius: 18, padding: 15, borderWidth: 1, borderColor: "#354536", gap: 10, marginTop: 4 }, feedbackTitle: { color: "#F4F7F0", fontSize: 16, fontWeight: "800" }, feedbackCopy: { color: muted, fontSize: 11, lineHeight: 16 }, feedbackInput: { minHeight: 82, color: "#F4F7F0", backgroundColor: "#111513", borderRadius: 12, padding: 12, textAlignVertical: "top", borderWidth: 1, borderColor: "#2D392E" }, feedbackButton: { backgroundColor: mint, borderRadius: 13, padding: 13, alignItems: "center" }, feedbackButtonText: { color: "#111513", fontWeight: "800" }, adminLink: { alignItems: "center", padding: 10 }, adminText: { color: mint, fontSize: 12, fontWeight: "800" }, note: { color: "#718071", fontSize: 11, lineHeight: 16, marginTop: 6 }
});
