import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
const mint = "#B8F36B"; const muted = "#A8B3A6";
const starter = ["eggs", "Greek yogurt", "rice", "spinach", "chicken", "berries"];
export default function RecipesScreen() { const [ingredients, setIngredients] = useState(starter); const [input, setInput] = useState(""); const add = () => { if (input.trim()) { setIngredients([...ingredients, input.trim()]); setInput(""); } }; return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.eyebrow}>PANTRY RECIPES</Text><Text style={styles.title}>Make what you have.</Text><Text style={styles.subtitle}>Add the ingredients in your kitchen and get balanced recipe ideas that fit your preferences and the time you have.</Text><View style={styles.addRow}><TextInput value={input} onChangeText={setInput} onSubmitEditing={add} placeholder="Add an ingredient" placeholderTextColor="#718071" style={styles.input} returnKeyType="done" /><Pressable style={styles.add} onPress={add}><Text style={styles.addText}>Add</Text></Pressable></View><View style={styles.chips}>{ingredients.map((item) => <View style={styles.chip} key={item}><Text style={styles.chipText}>{item}</Text></View>)}</View><View style={styles.filterRow}><Text style={styles.section}>Suggested for you</Text><Text style={styles.filter}>High protein · 25 min</Text></View><Recipe title="Spinach egg rice bowl" meta="26 g protein · 18 min" copy="Warm rice with soft eggs, wilted spinach, yogurt, and berries on the side." tags="Uses 4 ingredients" /><Recipe title="Greek yogurt berry bowl" meta="24 g protein · 5 min" copy="Yogurt, berries, toasted rice or oats, and a spoon of your preferred protein powder." tags="No-cook" /><Recipe title="Chicken and spinach skillet" meta="38 g protein · 22 min" copy="Sauté chicken and spinach, serve over rice, and season with lemon, herbs, or spices." tags="Uses 3 ingredients" /><Text style={styles.note}>Nutrition values are estimates and depend on brands, portions, and preparation. Adjust for allergies and dietary needs.</Text></ScrollView></ScreenContainer>; }
function Recipe({ title, meta, copy, tags }: { title: string; meta: string; copy: string; tags: string }) { return <View style={styles.recipe}><View style={styles.recipeTop}><View style={styles.recipeIcon}><Text style={styles.recipeEmoji}>⌁</Text></View><View style={{ flex: 1 }}><Text style={styles.recipeTitle}>{title}</Text><Text style={styles.recipeMeta}>{meta} · {tags}</Text></View></View><Text style={styles.recipeCopy}>{copy}</Text><Pressable><Text style={styles.view}>View recipe  ›</Text></Pressable></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, addRow: { flexDirection: "row", gap: 8, marginTop: 6 }, input: { flex: 1, backgroundColor: "#1B231D", color: "#F4F7F0", borderRadius: 13, padding: 13, borderWidth: 1, borderColor: "#2D392E" }, add: { backgroundColor: mint, borderRadius: 13, paddingHorizontal: 17, justifyContent: "center" }, addText: { color: "#111513", fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { backgroundColor: "#2B3B27", borderRadius: 12, paddingHorizontal: 11, paddingVertical: 8 }, chipText: { color: mint, fontSize: 12, fontWeight: "700" }, filterRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 5 }, section: { color: "#F4F7F0", fontSize: 18, fontWeight: "800" }, filter: { color: muted, fontSize: 11 }, recipe: { backgroundColor: "#1B231D", borderRadius: 19, padding: 16, gap: 11, borderWidth: 1, borderColor: "#263128" }, recipeTop: { flexDirection: "row", alignItems: "center", gap: 11 }, recipeIcon: { width: 45, height: 45, borderRadius: 14, backgroundColor: "#2C3321", alignItems: "center", justifyContent: "center" }, recipeEmoji: { color: mint, fontSize: 27 }, recipeTitle: { color: "#F4F7F0", fontSize: 15, fontWeight: "800" }, recipeMeta: { color: mint, fontSize: 11, fontWeight: "700", marginTop: 4 }, recipeCopy: { color: muted, fontSize: 12, lineHeight: 18 }, view: { color: mint, fontSize: 12, fontWeight: "800" }, note: { color: "#718071", fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 4 }
});
