import AsyncStorage from "@react-native-async-storage/async-storage";
import { CameraView, useCameraPermissions } from "expo-camera";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useRef, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { addFoodLog, type MealName } from "@/lib/food-log";
import { trpc } from "@/lib/trpc";

const mint = "#B8F36B"; const muted = "#A8B3A6";
type ScanMode = "food" | "supplement" | "pantry";
type VisionItem = { name: string; brand: string | null; confidence: number; servingDescription: string | null; calories: number | null; protein: number | null; carbohydrates: number | null; fat: number | null };

export default function ScanScreen() {
  const params = useLocalSearchParams<{ mode?: string; capture?: string }>(); const mode: ScanMode = params.mode === "supplement" || params.mode === "pantry" ? params.mode : "food";
  const { user } = useAuth({ autoFetch: false }); const userKey = user?.openId ?? (user?.id ? String(user.id) : "local-user");
  const camera = useRef<CameraView>(null); const [permission, requestPermission] = useCameraPermissions();
  const [captureMode, setCaptureMode] = useState<"photo" | "barcode">(params.capture === "barcode" ? "barcode" : "photo"); const [cameraOpen, setCameraOpen] = useState(false); const [barcode, setBarcode] = useState(""); const [paused, setPaused] = useState(false); const [meal, setMeal] = useState<MealName>("Snacks"); const [items, setItems] = useState<VisionItem[]>([]); const [notes, setNotes] = useState(""); const [message, setMessage] = useState("");
  const lookup = trpc.catalog.lookup.useQuery({ barcode }, { enabled: barcode.length >= 8 });
  const vision = trpc.scan.analyze.useMutation({ onSuccess: (data) => { setItems(data.items); setNotes(data.notes); setCameraOpen(false); setMessage(data.items.length ? "Review every match before saving." : "Nothing clear was identified. Try another angle or add it manually."); }, onError: () => setMessage("The photo could not be analysed. Check your connection and try a clear, well-lit photo.") });
  const barcodeItem = lookup.data?.matches[0]; const barcodeNutrition = useMemo(() => barcodeItem?.nutrients, [barcodeItem]);
  const title = mode === "pantry" ? "Scan pantry ingredients" : mode === "supplement" ? "Scan a supplement" : "Scan food";
  const takePhoto = async () => { const photo = await camera.current?.takePictureAsync({ quality: 0.45, base64: true, skipProcessing: false }); if (!photo?.base64) { setMessage("The photo was not captured. Please try again."); return; } setMessage("Identifying what is visible…"); vision.mutate({ imageDataUrl: `data:image/jpeg;base64,${photo.base64}`, mode }); };
  const saveNames = async (key: string, names: string[]) => { const raw = await AsyncStorage.getItem(key); const current: string[] = raw ? JSON.parse(raw) : []; await AsyncStorage.setItem(key, JSON.stringify([...new Set([...current, ...names])])); };
  const saveVision = async () => {
    if (!items.length) return;
    if (mode === "pantry") { await saveNames(`pulsecoach.pantry.${userKey}`, items.map((item) => item.name)); setMessage(`${items.length} ingredient${items.length === 1 ? "" : "s"} saved to your pantry.`); return; }
    if (mode === "supplement") { await saveNames(`pulsecoach.supplements.${userKey}`, items.map((item) => item.brand ? `${item.brand} ${item.name}` : item.name)); setMessage("Confirmed supplement saved to your cabinet."); return; }
    for (const item of items) await addFoodLog(userKey, { name: item.name, meal, servings: 1, servingDescription: item.servingDescription ?? "Photo estimate — confirm portion", nutrition: { calories: item.calories ?? 0, protein: item.protein ?? 0, carbohydrates: item.carbohydrates ?? 0, fat: item.fat ?? 0, sugars: 0, fibre: 0, sodium: 0 } });
    setMessage(`${items.length} food item${items.length === 1 ? "" : "s"} added to ${meal}. Review portions because photo nutrition is an estimate.`);
  };
  const saveBarcode = async () => {
    if (!barcodeItem) return;
    if (mode === "supplement") { await saveNames(`pulsecoach.supplements.${userKey}`, [`${barcodeItem.brand ?? ""} ${barcodeItem.name}`.trim()]); setMessage("Barcode product saved to your supplement cabinet."); return; }
    await addFoodLog(userKey, { name: barcodeItem.name, meal, servings: 1, servingDescription: "100 g label values — adjust serving", nutrition: { calories: barcodeNutrition?.calories ?? 0, protein: barcodeNutrition?.protein ?? 0, carbohydrates: barcodeNutrition?.carbohydrates ?? 0, fat: barcodeNutrition?.fat ?? 0, sugars: barcodeNutrition?.sugars ?? 0, fibre: barcodeNutrition?.fibre ?? 0, sodium: (barcodeNutrition?.sodium ?? 0) * 1000 } }); setMessage(`${barcodeItem.name} added to ${meal}. Confirm the serving amount from the package.`);
  };
  if (cameraOpen && permission?.granted) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5 pt-4"><View style={styles.cameraPage}><Pressable onPress={() => setCameraOpen(false)}><Text style={styles.back}>‹ Cancel</Text></Pressable><Text style={styles.cameraTitle}>{captureMode === "barcode" ? "Point at the barcode" : mode === "pantry" ? "Fit all ingredients in the frame" : "Take a clear photo"}</Text><View style={styles.cameraFrame}><CameraView ref={camera} style={StyleSheet.absoluteFillObject} facing="back" barcodeScannerSettings={{ barcodeTypes: ["ean13", "ean8", "upc_a", "upc_e", "code128", "qr"] }} onBarcodeScanned={captureMode === "barcode" && !paused ? ({ data }) => { setBarcode(data); setPaused(true); setCameraOpen(false); } : undefined} /></View>{captureMode === "photo" ? <Pressable style={styles.shutter} onPress={() => void takePhoto()} disabled={vision.isPending}><View style={styles.shutterInner} /></Pressable> : <Text style={styles.hint}>Scanning automatically…</Text>}</View></ScreenContainer>;
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>SMART CAMERA</Text><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>VELTURA will make its best match, show confidence, and ask you to confirm before anything is logged.</Text>
    {!permission?.granted ? <Pressable style={styles.primary} onPress={() => void requestPermission()}><Text style={styles.primaryText}>Allow camera access</Text></Pressable> : <View style={styles.actions}><Pressable style={styles.action} onPress={() => { setCaptureMode("photo"); setCameraOpen(true); }}><Text style={styles.actionTitle}>Take photo</Text><Text style={styles.actionCopy}>{mode === "pantry" ? "Several ingredients at once" : "Food, meal or product label"}</Text></Pressable><Pressable style={styles.action} onPress={() => { setCaptureMode("barcode"); setPaused(false); setCameraOpen(true); }}><Text style={styles.actionTitle}>Scan barcode</Text><Text style={styles.actionCopy}>Exact packaged-product lookup</Text></Pressable></View>}
    <Text style={styles.section}>Or enter barcode</Text><TextInput value={barcode} onChangeText={setBarcode} keyboardType="number-pad" placeholder="Barcode number" placeholderTextColor="#718071" style={styles.input} />{lookup.isFetching ? <Text style={styles.status}>Looking up the product…</Text> : null}{lookup.error ? <Text style={styles.warning}>The barcode service could not be reached. Try again when connected.</Text> : null}
    {mode === "food" ? <View style={styles.meals}>{(["Breakfast", "Lunch", "Dinner", "Snacks"] as MealName[]).map((name) => <Pressable key={name} onPress={() => setMeal(name)} style={[styles.meal, meal === name && styles.mealActive]}><Text style={[styles.mealText, meal === name && styles.mealTextActive]}>{name}</Text></Pressable>)}</View> : null}
    {barcodeItem ? <View style={styles.result}><Text style={styles.resultLabel}>BARCODE MATCH</Text><Text style={styles.resultTitle}>{barcodeItem.name}</Text><Text style={styles.resultMeta}>{barcodeItem.brand ?? "Brand not supplied"} · {barcodeItem.source}</Text><Pressable style={styles.primary} onPress={() => void saveBarcode()}><Text style={styles.primaryText}>Confirm and save</Text></Pressable></View> : null}
    {items.length ? <View style={styles.result}><Text style={styles.resultLabel}>PHOTO MATCHES</Text>{items.map((item, index) => <View key={`${item.name}-${index}`} style={styles.item}><View style={styles.flex}><Text style={styles.itemName}>{item.brand ? `${item.brand} ` : ""}{item.name}</Text><Text style={styles.resultMeta}>{item.servingDescription ?? "Portion needs confirmation"}</Text></View><Text style={[styles.confidence, item.confidence < 70 && styles.confidenceLow]}>{Math.round(item.confidence)}%</Text></View>)}{notes ? <Text style={styles.notes}>{notes}</Text> : null}<Pressable style={styles.primary} onPress={() => void saveVision()}><Text style={styles.primaryText}>{mode === "pantry" ? "Save ingredients to pantry" : "Confirm and save"}</Text></Pressable></View> : null}
    {message ? <Text style={message.includes("saved") || message.includes("added") ? styles.success : styles.warning}>{message}</Text> : null}<Text style={styles.note}>Photo recognition can be wrong, especially with mixed meals, hidden ingredients or unclear labels. Confirm foods, portions, allergens and supplement directions yourself.</Text>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 35 }, cameraPage: { flex: 1, gap: 15 }, back: { color: mint, fontWeight: "800" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "900" }, subtitle: { color: muted, lineHeight: 20 }, actions: { flexDirection: "row", gap: 10 }, action: { flex: 1, minHeight: 105, justifyContent: "center", padding: 14, borderRadius: 17, backgroundColor: "rgba(66, 132, 174, 0.38)", borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.58)" }, actionTitle: { color: mint, fontWeight: "900" }, actionCopy: { color: muted, fontSize: 10, lineHeight: 15, marginTop: 5 }, section: { color: "#F4F7F0", fontWeight: "900" }, input: { color: "#F4F7F0", backgroundColor: "rgba(10, 43, 67, 0.50)", borderRadius: 13, borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.58)", padding: 13 }, meals: { flexDirection: "row", gap: 6 }, meal: { flex: 1, padding: 9, alignItems: "center", borderRadius: 10, backgroundColor: "rgba(66, 132, 174, 0.38)" }, mealActive: { backgroundColor: mint }, mealText: { color: muted, fontSize: 9, fontWeight: "800" }, mealTextActive: { color: "#111513" }, result: { gap: 10, padding: 15, borderRadius: 18, backgroundColor: "rgba(76, 143, 184, 0.40)", borderWidth: 1, borderColor: "#405342" }, resultLabel: { color: mint, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, resultTitle: { color: "#F4F7F0", fontSize: 18, fontWeight: "900" }, resultMeta: { color: muted, fontSize: 10, marginTop: 3 }, item: { flexDirection: "row", alignItems: "center", gap: 10, borderTopWidth: 1, borderTopColor: "#354536", paddingTop: 9 }, flex: { flex: 1 }, itemName: { color: "#F4F7F0", fontWeight: "800" }, confidence: { color: mint, fontWeight: "900" }, confidenceLow: { color: "#F7CF77" }, notes: { color: muted, fontSize: 11, lineHeight: 16 }, primary: { backgroundColor: mint, padding: 14, alignItems: "center", borderRadius: 14 }, primaryText: { color: "#111513", fontWeight: "900" }, status: { color: mint, fontSize: 11 }, warning: { color: "#F7CF77", fontSize: 11, lineHeight: 16 }, success: { color: mint, fontSize: 11, lineHeight: 16, fontWeight: "800" }, note: { color: "#718071", fontSize: 10, lineHeight: 15, textAlign: "center" }, cameraTitle: { color: "#F4F7F0", fontSize: 22, fontWeight: "900" }, cameraFrame: { flex: 1, borderRadius: 24, overflow: "hidden", borderWidth: 2, borderColor: mint }, shutter: { alignSelf: "center", width: 72, height: 72, borderRadius: 36, borderWidth: 5, borderColor: mint, alignItems: "center", justifyContent: "center" }, shutterInner: { width: 54, height: 54, borderRadius: 27, backgroundColor: mint }, hint: { color: mint, textAlign: "center", fontWeight: "800" } });
