import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import * as Speech from "expo-speech";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
const mint = "#B8F36B"; const muted = "#A8B3A6";
export default function SessionScreen() { const [setCount, setSetCount] = useState(1); const [resting, setResting] = useState(false); const [finished, setFinished] = useState(false); return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5 pt-4"><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Exit session</Text></Pressable><View style={styles.top}><View><Text style={styles.eyebrow}>EXERCISE 1 OF 4</Text><Text style={styles.title}>Goblet squat</Text><Text style={styles.meta}>8–10 reps · Set {setCount} of 3</Text></View><View style={styles.timer}><Text style={styles.timerText}>{resting ? "01:30" : "00:00"}</Text><Text style={styles.timerLabel}>{resting ? "REST" : "READY"}</Text></View></View><View style={styles.formCard}><View style={styles.figure}><IconSymbol name="dumbbell.fill" size={42} color={mint} /></View><Text style={styles.formTitle}>{resting ? "Take your time." : "Move with control."}</Text><Text style={styles.formCopy}>{resting ? "Breathe, reset your stance, and start when you feel ready." : "Keep your chest tall, knees tracking over toes, and use a range that feels stable."}</Text></View><View style={styles.voice}><View style={styles.voiceIcon}><IconSymbol name="mic.fill" size={19} color={mint} /></View><Text style={styles.voiceText}>Say “next set”, “pause”, or “replace this exercise”.</Text></View><View style={styles.controls}><Pressable style={styles.secondary} onPress={() => setResting(!resting)}><IconSymbol name={resting ? "play.fill" : "pause.fill"} size={19} color={mint} /><Text style={styles.secondaryText}>{resting ? "Resume" : "Rest"}</Text></Pressable><Pressable style={styles.primary} onPress={() => { if (setCount < 3) { setSetCount(setCount + 1); setResting(true); Speech.stop(); Speech.speak(`Set complete. Rest for 90 seconds, then prepare for set ${setCount + 1}.`); } else { setFinished(true); Speech.stop(); Speech.speak("Session complete. Nice work. Cool down and notice how you feel."); } }}><Text style={styles.primaryText}>{finished ? "Session saved" : setCount < 3 ? "Complete set" : "Finish session"}</Text><IconSymbol name={finished ? "checkmark" : "chevron.right"} size={20} color="#111513" /></Pressable></View>{finished && <Text style={styles.success}>Nice work. Your session is saved locally. Keep the next choice simple: hydrate, cool down, and notice how you feel.</Text>}<Text style={styles.note}>Stop if you feel sharp pain, dizziness, or unusual symptoms.</Text></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, paddingBottom: 20, gap: 18 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginTop: 10 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { color: "#F4F7F0", fontSize: 32, fontWeight: "800", marginTop: 8, letterSpacing: -0.7 }, meta: { color: muted, fontSize: 14, marginTop: 5 }, timer: { width: 78, height: 78, borderRadius: 39, borderWidth: 3, borderColor: mint, alignItems: "center", justifyContent: "center" }, timerText: { color: "#F4F7F0", fontWeight: "800", fontSize: 17 }, timerLabel: { color: mint, fontSize: 9, fontWeight: "800", marginTop: 2 }, formCard: { flex: 1, minHeight: 290, backgroundColor: "#1B231D", borderRadius: 25, borderWidth: 1, borderColor: "#2D392E", alignItems: "center", justifyContent: "center", padding: 25 }, figure: { width: 100, height: 100, borderRadius: 32, backgroundColor: "#2C3321", alignItems: "center", justifyContent: "center", marginBottom: 25 }, formTitle: { color: "#F4F7F0", fontSize: 22, fontWeight: "800", textAlign: "center" }, formCopy: { color: muted, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 9, maxWidth: 265 }, voice: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#202A21", borderRadius: 16, padding: 13 }, voiceIcon: { width: 32, height: 32, borderRadius: 11, backgroundColor: "#2B3B27", alignItems: "center", justifyContent: "center" }, voiceText: { color: "#DCE5D8", fontSize: 12, lineHeight: 17, flex: 1 }, controls: { flexDirection: "row", gap: 10 }, secondary: { flex: 0.8, backgroundColor: "#1B231D", borderRadius: 16, padding: 15, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7, borderWidth: 1, borderColor: "#2D392E" }, secondaryText: { color: mint, fontWeight: "800" }, primary: { flex: 1.4, backgroundColor: mint, borderRadius: 16, padding: 15, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 }, primaryText: { color: "#111513", fontWeight: "800", fontSize: 14 }, success: { color: mint, fontSize: 12, lineHeight: 17, textAlign: "center" }, note: { color: "#718071", fontSize: 11, lineHeight: 16, textAlign: "center" }
});
