import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
const mint = "#B8F36B"; const muted = "#A8B3A6";
const categories = ["Weight trend", "BMI", "Steps", "Workouts", "Active minutes", "Calories", "Nutrition progress", "Route breadcrumbs"];
export default function SharingScreen() { const [selected, setSelected] = useState<string[]>(["Steps", "Workouts"]); const friend = "Jordan M."; const visible = useMemo(() => categories.filter((item) => selected.includes(item)), [selected]); const toggle = (item: string) => setSelected((items) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item]); return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.eyebrow}>SHARING CONTROLS</Text><Text style={styles.title}>You choose what’s visible.</Text><Text style={styles.subtitle}>Sharing is private by default. Set different permissions for each friend and change them whenever you want.</Text><View style={styles.friendCard}><View style={styles.avatar}><Text style={styles.avatarText}>JM</Text></View><View><Text style={styles.friendName}>{friend}</Text><Text style={styles.friendMeta}>Friend-specific permissions</Text></View></View><Text style={styles.section}>Share with {friend}</Text><View style={styles.list}>{categories.map((item) => <View style={styles.item} key={item}><View style={{ flex: 1 }}><Text style={styles.itemTitle}>{item}</Text><Text style={styles.itemCopy}>{item === "Route breadcrumbs" ? "Where you travelled today" : item === "BMI" ? "Your latest BMI estimate" : `Your ${item.toLowerCase()} summary`}</Text></View><Switch value={selected.includes(item)} onValueChange={() => toggle(item)} trackColor={{ false: "#39433A", true: "#78994A" }} thumbColor={selected.includes(item) ? mint : "#A8B3A6"} /></View>)}</View><View style={styles.preview}><Text style={styles.previewTitle}>What {friend} can see</Text>{visible.length ? visible.map((item) => <Text key={item} style={styles.previewItem}>• {item}</Text>) : <Text style={styles.previewItem}>• Nothing shared</Text>}<Text style={styles.previewCopy}>Competition data is limited to the metric selected for that competition. Route breadcrumbs remain off unless explicitly enabled here.</Text></View><Pressable style={styles.save} onPress={() => router.back()}><Text style={styles.saveText}>Save sharing choices</Text></Pressable><Pressable style={styles.revoke} onPress={() => setSelected([])}><Text style={styles.revokeText}>Revoke all access for {friend}</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 15 }, back: { color: mint, fontSize: 15, fontWeight: "700" }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800" }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, friendCard: { backgroundColor: "rgba(76, 143, 184, 0.40)", borderRadius: 18, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.54)" }, avatar: { width: 43, height: 43, borderRadius: 14, backgroundColor: "rgba(54, 119, 161, 0.46)", alignItems: "center", justifyContent: "center" }, avatarText: { color: mint, fontWeight: "900" }, friendName: { color: "#F4F7F0", fontWeight: "800", fontSize: 15 }, friendMeta: { color: muted, fontSize: 11, marginTop: 3 }, section: { color: "#F4F7F0", fontWeight: "800", fontSize: 18, marginTop: 4 }, list: { backgroundColor: "rgba(66, 132, 174, 0.38)", borderRadius: 18, borderWidth: 1, borderColor: "rgba(174, 224, 255, 0.40)", overflow: "hidden" }, item: { padding: 14, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "#263128" }, itemTitle: { color: "#F4F7F0", fontSize: 13, fontWeight: "800" }, itemCopy: { color: muted, fontSize: 10, marginTop: 4 }, preview: { backgroundColor: "rgba(54, 119, 161, 0.46)", borderRadius: 17, padding: 15, borderWidth: 1, borderColor: mint }, previewTitle: { color: mint, fontWeight: "900", fontSize: 14 }, previewItem: { color: "#F4F7F0", fontSize: 12, marginTop: 7 }, previewCopy: { color: "#DCE5D8", fontSize: 10, lineHeight: 15, marginTop: 11 }, save: { backgroundColor: mint, borderRadius: 15, padding: 15, alignItems: "center" }, saveText: { color: "#111513", fontWeight: "800" }, revoke: { alignItems: "center", padding: 10 }, revokeText: { color: "#F7CF77", fontWeight: "800", fontSize: 12 }
});
