export type HealthSample = { uuid?: string; quantity: number; startDate: Date | string; endDate: Date | string; sourceName?: string };
export type MovementSummary = { steps?: number; distanceMeters?: number; activeEnergyKcal?: number; exerciseMinutes?: number; heartRateAverage?: number; weightKg?: number; sleepMinutes?: number };
export type ChartBucket = { label: string; start: Date; end: Date; value: number };
const dateOf = (value: Date | string) => value instanceof Date ? value : new Date(value);
const fingerprint = (sample: HealthSample) => sample.uuid ? `uuid:${sample.uuid}` : [sample.sourceName ?? "unknown", dateOf(sample.startDate).getTime(), dateOf(sample.endDate).getTime(), sample.quantity].join(":");
export function dedupeSamples(samples: readonly HealthSample[]) { const seen = new Set<string>(); return samples.filter((sample) => { const key = fingerprint(sample); if (seen.has(key)) return false; seen.add(key); return true; }); }
export function mergeIncrementalSamples(cached: readonly HealthSample[], received: readonly HealthSample[], deletedUuids: readonly string[] = []) { const deleted = new Set(deletedUuids); const receivedIds = new Set(received.flatMap((sample) => sample.uuid ? [sample.uuid] : [])); return dedupeSamples([...cached.filter((sample) => !sample.uuid || (!deleted.has(sample.uuid) && !receivedIds.has(sample.uuid))), ...received]); }
export function sumSamples(samples: readonly HealthSample[]) { return dedupeSamples(samples).reduce((total, sample) => total + sample.quantity, 0); }
export function averageSamples(samples: readonly HealthSample[]) { const unique = dedupeSamples(samples); return unique.length ? unique.reduce((total, sample) => total + sample.quantity, 0) / unique.length : undefined; }
export function localDayBounds(reference: Date) { const start = new Date(reference); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { start, end }; }
export function makeDayBuckets(reference: Date, days: number) { const first = new Date(reference); first.setHours(0, 0, 0, 0); first.setDate(first.getDate() - (days - 1)); return Array.from({ length: days }, (_, index) => { const start = new Date(first); start.setDate(first.getDate() + index); const end = new Date(start); end.setDate(end.getDate() + 1); return { label: start.toLocaleDateString("en-AU", { day: "numeric", month: "short" }), start, end, value: 0 }; }); }
export function bucketSamples(samples: readonly HealthSample[], buckets: ChartBucket[]) { const unique = dedupeSamples(samples); return buckets.map((bucket) => ({ ...bucket, value: unique.filter((sample) => { const start = dateOf(sample.startDate); return start >= bucket.start && start < bucket.end; }).reduce((total, sample) => total + sample.quantity, 0) })); }
