import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAuth } from "@/hooks/use-auth";
import { loadFoodLog, type FoodLogEntry } from "@/lib/food-log";
import { loadIndoorCardio, type IndoorCardioEntry } from "@/lib/indoor-cardio";
import { loadCompletedWorkouts, type CompletedWorkout } from "@/lib/workout-log";
const mint = "#B8F36B"; const muted = "#A8B3A6";
type Activity = { completedAt: string; label: string };
const dayKey = (date: Date) => `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
const startOfWeek = (now: Date) => { const date = new Date(now); const weekday = (date.getDay() + 6) % 7; date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - weekday); return date; };
export default function ProgressScreen() {
  const { user } = useAuth({ autoFetch: false }); const userKey = user?.openId ?? (user?.id ? String(user.id) : "local-user"); const [activities, setActivities] = useState<Activity[]>([]); const [foods, setFoods] = useState<FoodLogEntry[]>([]); const [selected, setSelected] = useState(dayKey(new Date()));
  useFocusEffect(useCallback(() => { let active = true; void Promise.all([AsyncStorage.getItem(`pulsecoach.runs.${userKey}`), AsyncStorage.getItem(`pulsecoach.walks.${userKey}`), AsyncStorage.getItem(`pulsecoach.rides.${userKey}`), loadCompletedWorkouts(userKey), loadIndoorCardio(userKey), loadFoodLog(userKey)]).then(([runs, walks, rides, workouts, indoor, food]) => { if (!active) return; const parse = (raw: string | null, label: string): Activity[] => { try { return (raw ? JSON.parse(raw) : []).map((item: any) => ({ completedAt: item.completedAt, label })); } catch { return []; } }; setActivities([...parse(runs, "Outdoor run"), ...parse(walks, "Outdoor walk"), ...parse(rides, "Outdoor ride"), ...workouts.map((item: CompletedWorkout) => ({ completedAt: item.completedAt, label: item.title })), ...indoor.map((item: IndoorCardioEntry) => ({ completedAt: item.completedAt, label: item.type }))]); setFoods(food); }); return () => { active = false; }; }, [userKey]));
  const days = useMemo(() => { const monday = startOfWeek(new Date()); return Array.from({ length: 7 }, (_, index) => { const date = new Date(monday); date.setDate(monday.getDate() + index); return date; }); }, []);
  const selectedDate = days.find((date) => dayKey(date) === selected) ?? new Date(); const selectedActivities = activities.filter((item) => dayKey(new Date(item.completedAt)) === selected); const selectedFoods = foods.filter((item) => dayKey(new Date(item.createdAt)) === selected); const achieved = new Set([...activities.map((item) => dayKey(new Date(item.completedAt))), ...foods.map((item) => dayKey(new Date(item.createdAt)))]);
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PROGRESS</Text><Text style={styles.title}>Notice what’s working.</Text><Text style={styles.subtitle}>Tap any day to check what you recorded and achieved.</Text><View style={styles.week}><Text style={styles.weekLabel}>THIS WEEK</Text><Text style={styles.weekTitle}>{days[0].toLocaleDateString("en-AU", { day: "numeric", month: "short" })} – {days[6].toLocaleDateString("en-AU", { day: "numeric", month: "short" })}</Text><View style={styles.days}>{days.map((date) => { const key = dayKey(date); const today = key === dayKey(new Date()); const done = achieved.has(key); return <Pressable style={styles.day} key={key} onPress={() => setSelected(key)}><View style={[styles.dayDot, done && styles.dayDone, today && styles.dayToday, selected === key && styles.daySelected]}><Text style={[styles.dayDotText, done && { color: "#111513" }]}>{done ? "✓" : date.getDate()}</Text></View><Text style={[styles.dayText, today && styles.todayText]}>{date.toLocaleDateString("en-AU", { weekday: "narrow" })}</Text></Pressable>; })}</View><View style={styles.detail}><Text style={styles.detailTitle}>{selectedDate.toLocaleDateString("en-AU", { weekday: "long", day: "numeric", month: "long" })}</Text>{selectedActivities.map((item, index) => <Text key={`${item.completedAt}-${index}`} style={styles.detailItem}>✓ {item.label}</Text>)}{selectedFoods.length ? <Text style={styles.detailItem}>✓ {selectedFoods.length} food entr{selectedFoods.length === 1 ? "y" : "ies"} logged</Text> : null}{!selectedActivities.length && !selectedFoods.length ? <Text style={styles.detailEmpty}>Nothing recorded for this day yet.</Text> : null}</View></View><Text style={styles.section}>Your signals</Text><View style={styles.signal}><View style={styles.signalIcon}><IconSymbol name="dumbbell.fill" size={21} color={mint} /></View><View style={{ flex: 1 }}><Text style={styles.signalTitle}>Training this week</Text><Text style={styles.signalCopy}>{activities.filter((item) => days.some((date) => dayKey(date) === dayKey(new Date(item.completedAt)))).length} recorded session(s)</Text></View></View><Pressable style={styles.action} onPress={() => router.push("/history" as any)}><Text style={styles.actionText}>Open full activity history</Text><Text style={styles.actionArrow}>›</Text></Pressable><Pressable style={styles.action} onPress={() => router.push("/wellness" as any)}><Text style={styles.actionText}>Open health and wellness</Text><Text style={styles.actionArrow}>›</Text></Pressable><Text style={styles.note}>Days reflect records saved on this phone and connected health sources. Missing data is never invented.</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 16 }, eyebrow: { color: mint, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#F4F7F0", fontSize: 30, fontWeight: "800" }, subtitle: { color: muted, fontSize: 14, lineHeight: 20 }, week: { backgroundColor: "#202A21", borderRadius: 21, padding: 18, borderWidth: 1, borderColor: "#354536", gap: 10 }, weekLabel: { color: mint, fontSize: 10, fontWeight: "800", letterSpacing: 1.2 }, weekTitle: { color: "#F4F7F0", fontSize: 18, fontWeight: "800" }, days: { flexDirection: "row", justifyContent: "space-between", marginTop: 7 }, day: { alignItems: "center", gap: 6 }, dayDot: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#303A31", alignItems: "center", justifyContent: "center" }, dayDone: { backgroundColor: mint }, dayToday: { borderWidth: 2, borderColor: "#87C7E8" }, daySelected: { transform: [{ scale: 1.12 }] }, dayDotText: { color: muted, fontSize: 11, fontWeight: "800" }, dayText: { color: muted, fontSize: 10, fontWeight: "700" }, todayText: { color: "#87C7E8" }, detail: { backgroundColor: "#182019", borderRadius: 14, padding: 13, gap: 6, marginTop: 5 }, detailTitle: { color: "#F4F7F0", fontWeight: "900" }, detailItem: { color: mint, fontSize: 12 }, detailEmpty: { color: muted, fontSize: 12 }, section: { color: "#F4F7F0", fontSize: 18, fontWeight: "800" }, signal: { backgroundColor: "#1B231D", borderRadius: 18, padding: 15, flexDirection: "row", alignItems: "center", gap: 12 }, signalIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: "#2B3B27", alignItems: "center", justifyContent: "center" }, signalTitle: { color: "#F4F7F0", fontWeight: "800" }, signalCopy: { color: muted, fontSize: 12, marginTop: 3 }, action: { backgroundColor: "#2B3B27", borderRadius: 15, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1, borderColor: mint }, actionText: { color: mint, fontWeight: "800", fontSize: 13 }, actionArrow: { color: mint, fontSize: 24 }, note: { color: "#718071", fontSize: 11, lineHeight: 16 } });
