import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { useAuth } from "../../hooks/use-auth";
import { loadProfilePreferences, saveProfilePreferences } from "../../lib/profile-preferences";
import { DEFAULT_USER_SETTINGS, type UserSettings } from "../../shared/settings-preferences";
import { settingsSection } from "../../lib/settings-screen-config";

type Field = { path:string; label:string; kind?:"toggle"|"choice"|"number"|"text"; choices?:string[]; help?:string };
const fields: Record<string, Field[]> = {
  "profile-health":[{path:"profileHealth.profilePhotoUri",label:"Profile photo"},{path:"profileHealth.dateOfBirth",label:"Date of birth"},{path:"profileHealth.gender",label:"Sex / gender"},{path:"profileHealth.fitnessLevel",label:"Fitness level"},{path:"profileHealth.activityType",label:"Activity type"},{path:"profileHealth.emergencyContact",label:"Emergency contact"},{path:"profileHealth.restingHeartRate",label:"Resting heart rate",kind:"number"},{path:"profileHealth.maximumHeartRate",label:"Maximum heart rate",kind:"number"},{path:"profileHealth.vo2Max",label:"VO2 max",kind:"number"},{path:"profileHealth.bodyFatPercentage",label:"Body-fat percentage",kind:"number"},{path:"profileHealth.medicalConditions",label:"Medical conditions"},{path:"profileHealth.wheelchairMode",label:"Wheelchair mode",kind:"toggle"},{path:"profileHealth.pregnancyMode",label:"Pregnancy mode",kind:"toggle"}],
  goals:[{path:"goals.daily.steps",label:"Daily steps",kind:"number"},{path:"goals.daily.calorieIntakeTarget",label:"Your chosen daily calorie target",kind:"number",help:"This is the target you selected."},{path:"goals.daily.pulseCoachEstimatedCalories",label:"PulseCoach estimated calorie target",kind:"number",help:"Calculated from your profile and activity."},{path:"goals.daily.useEstimatedCalories",label:"Use PulseCoach estimate as active target",kind:"toggle"},{path:"goals.daily.caloriesBurned",label:"Calories burned",kind:"number"},{path:"goals.daily.activeMinutes",label:"Active minutes",kind:"number"},{path:"goals.daily.distance",label:"Daily distance",kind:"number"},{path:"goals.daily.floorsClimbed",label:"Floors climbed",kind:"number"},{path:"goals.daily.sleepDuration",label:"Sleep duration",kind:"number"},{path:"goals.daily.waterIntake",label:"Water intake",kind:"number"},{path:"goals.weekly.runningDistance",label:"Weekly running distance",kind:"number"},{path:"goals.weekly.cyclingDistance",label:"Weekly cycling distance",kind:"number"},{path:"goals.weekly.strengthSessions",label:"Strength sessions",kind:"number"},{path:"goals.weekly.gymSessions",label:"Gym sessions",kind:"number"},{path:"goals.longTerm.weightGoal",label:"Weight goal",kind:"number"},{path:"goals.longTerm.bodyFatGoal",label:"Body-fat goal",kind:"number"},{path:"goals.longTerm.strengthTargets",label:"Strength targets"},{path:"goals.longTerm.customGoals",label:"Custom goals"}],
  "units":[{path:"units.distance",label:"Distance",kind:"choice",choices:["kilometres","miles"]},{path:"units.weight",label:"Weight",kind:"choice",choices:["kilograms","pounds"]},{path:"units.height",label:"Height",kind:"choice",choices:["centimetres","feet/inches"]},{path:"units.temperature",label:"Temperature",kind:"choice",choices:["Celsius","Fahrenheit"]},{path:"units.energy",label:"Energy",kind:"choice",choices:["kcal","kJ"]},{path:"units.pace",label:"Pace",kind:"choice",choices:["min/km","min/mile"]},{path:"units.speed",label:"Speed",kind:"choice",choices:["km/h","mph"]}],
  workout:[...(["autoStartDetection","autoPause","voiceFeedback","captions","hapticFeedback"].map((p):Field=>({path:"workout."+p,label:p.replace(/[A-Z]/g,(m)=>" "+m).replace(/^./,(m)=>m.toUpperCase()),kind:"toggle"}))), ...([{path:"workout.audioLanguage",label:"Audio language"},{path:"workout.musicPriority",label:"Music priority"},{path:"workout.equipment.availability",label:"Equipment availability"},{path:"workout.equipment.homeGym",label:"Home gym"},{path:"workout.equipment.currentWorkoutGym",label:"Current workout gym"}] as Field[])],
  wellness:[{path:"wellness.sleep",label:"Sleep",kind:"toggle"},{path:"wellness.nutrition",label:"Nutrition",kind:"toggle"},{path:"wellness.mindfulness",label:"Mindfulness",kind:"toggle"}],
  "coaching-ai":[{path:"coachingAI.adaptiveTraining",label:"Adaptive training",kind:"toggle"},{path:"coachingAI.difficultyAutoAdjustment",label:"Difficulty auto-adjustment",kind:"toggle"},{path:"coachingAI.injuryRecoveryMode",label:"Injury-recovery mode",kind:"toggle"},{path:"coachingAI.aiNutritionSuggestions",label:"AI nutrition suggestions",kind:"toggle"},{path:"coachingAI.aiSleepOptimisation",label:"AI sleep optimisation",kind:"toggle"},{path:"coachingAI.weeklyTrainingPlan",label:"Weekly training plan",kind:"toggle"},{path:"coachingAI.preferredWorkoutTypes",label:"Preferred workout types"},{path:"coachingAI.coachingStyle",label:"Preferred coaching style"},{path:"coachingAI.humourLevel",label:"Coaching humour level",kind:"choice",choices:["low","medium","high"]},{path:"coachingAI.musicGenres",label:"Music genres"},{path:"coachingAI.equipmentAvailability",label:"Equipment availability"}],
  "social-community":[{path:"socialCommunity.groupVisibility",label:"Group visibility",kind:"choice",choices:["friends","local","state","national","global"]},{path:"socialCommunity.leaderboardPrivacy",label:"Leaderboard privacy",kind:"choice",choices:["private","friends","local","state","national","global"]},{path:"socialCommunity.automaticallyShareWorkouts",label:"Automatically share workouts",kind:"toggle"},{path:"socialCommunity.shareAchievements",label:"Share achievements",kind:"toggle"},{path:"socialCommunity.shareRoutes",label:"Share routes",kind:"toggle"}],
  notifications:[{path:"notifications.workoutNotifications",label:"Workout notifications",kind:"toggle"},{path:"notifications.healthNotifications",label:"Health notifications",kind:"toggle"},{path:"notifications.mealLoggingReminders",label:"Meal-logging reminders",kind:"toggle"},{path:"notifications.motivationalMessages",label:"Motivational messages",kind:"toggle"},{path:"notifications.appNotifications",label:"App notifications",kind:"toggle"}],
  "privacy-permissions":[{path:"privacyPermissions.activityTracking",label:"Activity tracking",kind:"toggle"},{path:"privacyPermissions.foregroundLocationTracking",label:"Foreground location tracking",kind:"toggle"},{path:"privacyPermissions.heartRateAccess",label:"Heart-rate access",kind:"toggle"},{path:"privacyPermissions.sleepTracking",label:"Sleep tracking",kind:"toggle"},{path:"privacyPermissions.menstrualCycleTracking",label:"Menstrual-cycle tracking",kind:"toggle"},{path:"privacyPermissions.publicProfile",label:"Public profile",kind:"toggle"},{path:"privacyPermissions.leaderboardVisibility",label:"Leaderboard visibility",kind:"toggle"},{path:"privacyPermissions.routeSharing",label:"Route sharing",kind:"toggle"},{path:"privacyPermissions.friendDiscovery",label:"Friend discovery",kind:"toggle"}],
  "app-settings":[{path:"app.theme",label:"Theme",kind:"choice",choices:["system","light","dark"]},{path:"app.textSize",label:"Text sizing",kind:"choice",choices:["standard","large"]},{path:"app.reducedMotion",label:"Reduced motion",kind:"toggle"},{path:"app.highContrast",label:"High contrast",kind:"toggle"},{path:"app.language",label:"Language"},{path:"app.offlineData",label:"Offline data",kind:"toggle"},{path:"app.cacheManagement",label:"Cache management"},{path:"app.diagnostics",label:"Diagnostics"}],
};

const readPath=(obj:any,path:string)=>path.split(".").reduce((v,k)=>v?.[k],obj);
const writePath=(obj:any,path:string,value:any)=>{const copy=JSON.parse(JSON.stringify(obj)); const parts=path.split("."); let target=copy; parts.slice(0,-1).forEach((p)=>{target[p]??={}; target=target[p];}); target[parts.at(-1)!]=value; return copy;};
const merge=(base:any,value:any):any=>Object.keys(base).reduce((out,key)=>({...out,[key]:base[key]&&typeof base[key]==="object"&&!Array.isArray(base[key])?merge(base[key],value?.[key]):value?.[key]??base[key]}),{});

export default function SettingsSectionScreen(){
  const router=useRouter(); const {section}=useLocalSearchParams<{section:string}>(); const config=useMemo(()=>settingsSection(section||""),[section]); const {user}=useAuth();
  const [settings,setSettings]=useState<UserSettings>(DEFAULT_USER_SETTINGS); const [profile,setProfile]=useState<any>(); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [reloadKey,setReloadKey]=useState(0);
  const load=useCallback(async()=>{if(!user?.openId)return; setLoading(true);setError(null);try{const p=await loadProfilePreferences(user.openId);setProfile(p);setSettings(merge(DEFAULT_USER_SETTINGS,p.settings) as UserSettings);}catch(e){setError(e instanceof Error?e.message:"Unable to load settings.");}finally{setLoading(false);}},[user?.openId]); useFocusEffect(useCallback(()=>{void reloadKey;void load();},[load,reloadKey]));
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color="#5eead4"/><Text style={styles.muted}>Loading {config?.title||"settings"}…</Text></View>;
  if(error)return <View style={styles.center}><Text style={styles.title}>Unable to load settings</Text><Text style={styles.muted}>{error}</Text><Pressable style={styles.button} onPress={()=>setReloadKey((v)=>v+1)}><Text style={styles.buttonText}>Retry</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.back()}><Text style={styles.buttonText}>Back</Text></Pressable></View>;
  if(!config||!profile)return <View style={styles.center}><Text style={styles.title}>Settings screen unavailable</Text><Pressable style={styles.secondary} onPress={()=>router.back()}><Text style={styles.buttonText}>Back</Text></Pressable></View>;
  const sectionFields=fields[config.id]||[]; const update=(path:string,value:any)=>{setSaved(false);const current=readPath(settings,path);if(typeof current==="number")value=value===""?0:Number(value);else if(current&&typeof current==="object")try{value=JSON.parse(value)}catch{return};setSettings(writePath(settings,path,value));};
  const save=async()=>{if(!user||!profile)return;setSaving(true);setError(null);try{await saveProfilePreferences(user.openId,{...profile,settings});setSaved(true);}catch(e){setError(e instanceof Error?e.message:"Unable to save settings.");}finally{setSaving(false);}};
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.heading}>{config.title}</Text><Text style={styles.muted}>{config.description}</Text><View style={styles.card}>{sectionFields.map((f)=><SettingField key={f.path} field={f} value={readPath(settings,f.path)} onChange={(v)=>update(f.path,v)}/>)}</View>{config.id==="profile-health"&&<Pressable style={styles.link} onPress={()=>router.push("/(profile)/personal-details" as any)}><Text style={styles.linkText}>Open Personal Details</Text></Pressable>}{config.id==="workout"&&<><Pressable style={styles.link} onPress={()=>router.push("/scan" as any)}><Text style={styles.linkText}>Open Machine Scanner</Text></Pressable><Pressable style={styles.link} onPress={()=>router.push("/gym-directory" as any)}><Text style={styles.linkText}>Open Gym Directory</Text></Pressable></>}{config.id==="privacy-permissions"&&<><Text style={styles.note}>Permission switches reflect your preference. Operating-system access is only enabled after the OS grants it.</Text><Pressable style={styles.link} onPress={()=>router.push("/(profile)/health" as any)}><Text style={styles.linkText}>Review Apple Health permissions</Text></Pressable><Pressable style={styles.danger} onPress={()=>Alert.alert("Delete account data?","This permanently removes your account data and cannot be undone.",[ {text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>{}}])}><Text style={styles.dangerText}>Delete account data</Text></Pressable></>}{config.id==="about"&&<View style={styles.card}><Text style={styles.rowTitle}>PulseCoach</Text><Text style={styles.muted}>Version and build information</Text><Text style={styles.muted}>Terms · Privacy policy · Support · Licences</Text></View>}<Pressable disabled={saving} style={styles.button} onPress={()=>void save()}><Text style={styles.buttonText}>{saving?"Saving…":"Save changes"}</Text></Pressable>{saved&&<Text style={styles.success}>Saved</Text>}</ScrollView>;
}

function SettingField({field,value,onChange}:{field:Field;value:any;onChange:(v:any)=>void}){if(field.kind==="toggle")return <View style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{field.label}</Text>{field.help&&<Text style={styles.muted}>{field.help}</Text>}</View><Switch value={Boolean(value)} onValueChange={onChange}/></View>;if(field.kind==="choice")return <View style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{field.label}</Text><View style={styles.choices}>{field.choices?.map((c)=><Pressable key={c} style={[styles.choice,c===value&&styles.choiceActive]} onPress={()=>onChange(c)}><Text style={styles.choiceText}>{c}</Text></Pressable>)}</View></View></View>;return <View style={styles.row}><Text style={styles.rowTitle}>{field.label}</Text><TextInput value={value==null?"":typeof value==="object"?JSON.stringify(value):String(value)} onChangeText={onChange} keyboardType={field.kind==="number"?"numeric":"default"} placeholder="Not set" placeholderTextColor="#71839a" style={styles.input}/>{field.help&&<Text style={styles.muted}>{field.help}</Text>}</View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:"#07111f"},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24,backgroundColor:"#07111f"},heading:{fontSize:28,fontWeight:"800",color:"#fff",marginTop:10},title:{fontSize:20,fontWeight:"700",color:"#fff",textAlign:"center"},back:{color:"#5eead4",fontSize:16},muted:{color:"#9fb0c5",marginTop:4},card:{backgroundColor:"#102033",borderRadius:16,marginTop:20,overflow:"hidden"},row:{padding:16,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#294057",gap:8},rowTitle:{fontSize:16,fontWeight:"700",color:"#fff"},input:{color:"#fff",borderWidth:1,borderColor:"#40536a",borderRadius:8,padding:10,marginTop:8},choices:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:8},choice:{paddingHorizontal:10,paddingVertical:7,borderRadius:8,backgroundColor:"#294057"},choiceActive:{backgroundColor:"#0d9488"},choiceText:{color:"#fff"},button:{backgroundColor:"#14b8a6",borderRadius:10,padding:14,alignItems:"center",marginTop:20},secondary:{backgroundColor:"#294057",borderRadius:10,padding:14,alignItems:"center",marginTop:12},buttonText:{color:"#fff",fontWeight:"700"},actions:{flexDirection:"row",gap:12},success:{color:"#5eead4",textAlign:"center",marginTop:10},link:{padding:16,backgroundColor:"#17324a",borderRadius:10,marginTop:12},linkText:{color:"#5eead4",fontWeight:"700"},note:{color:"#f4c97b",marginTop:16},danger:{padding:16,borderRadius:10,marginTop:20,borderWidth:1,borderColor:"#a33d4b"},dangerText:{color:"#ff8f9c",fontWeight:"700"}}
);
